package com.hm.contract.model;

import java.util.Date;

import com.gep.core.util.InputChecker;
import com.gep.core.util.OssOpsUtils;

/**
 * @ClassName: LnContracttInfo
 * @Description: 贷款合同文件
 * @author qiuyuan
 * @date 2016年4月11日 下午2:26:04
 * @Copyright (c) 2016, 9fchaoneng.com All Rights Reserved.
 */
public class LnContracttInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.CONTRACT_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.CONTRACT_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.CONTRACT_FILESIZE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Double contractFilesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.CONTRACT_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date contractTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.FILENO
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String fileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.URL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date createdon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date modifiedon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.OSS_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String ossId;
    
    /**
	 * ossId地址
	 */
	private String ossIdUrl;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.TEMPLET_OSSID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String templetOssid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.CONTRACT_CATEGORY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contractCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_contractt_info.FIRM_STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String firmStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.ID
     *
     * @return the value of ln_contractt_info.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.ID
     *
     * @param id the value for ln_contractt_info.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.APP_ID
     *
     * @return the value of ln_contractt_info.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.APP_ID
     *
     * @param appId the value for ln_contractt_info.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.CONTRACT_TYPE
     *
     * @return the value of ln_contractt_info.CONTRACT_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.CONTRACT_TYPE
     *
     * @param contractType the value for ln_contractt_info.CONTRACT_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractType(String contractType) {
        this.contractType = contractType == null ? null : contractType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.CONTRACT_NAME
     *
     * @return the value of ln_contractt_info.CONTRACT_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.CONTRACT_NAME
     *
     * @param contractName the value for ln_contractt_info.CONTRACT_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.CONTRACT_FILESIZE
     *
     * @return the value of ln_contractt_info.CONTRACT_FILESIZE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Double getContractFilesize() {
        return contractFilesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.CONTRACT_FILESIZE
     *
     * @param contractFilesize the value for ln_contractt_info.CONTRACT_FILESIZE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractFilesize(Double contractFilesize) {
        this.contractFilesize = contractFilesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.CONTRACT_TIME
     *
     * @return the value of ln_contractt_info.CONTRACT_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getContractTime() {
        return contractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.CONTRACT_TIME
     *
     * @param contractTime the value for ln_contractt_info.CONTRACT_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractTime(Date contractTime) {
        this.contractTime = contractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.STATUS
     *
     * @return the value of ln_contractt_info.STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.STATUS
     *
     * @param status the value for ln_contractt_info.STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.FILENO
     *
     * @return the value of ln_contractt_info.FILENO
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getFileno() {
        return fileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.FILENO
     *
     * @param fileno the value for ln_contractt_info.FILENO
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFileno(String fileno) {
        this.fileno = fileno == null ? null : fileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.URL
     *
     * @return the value of ln_contractt_info.URL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.URL
     *
     * @param url the value for ln_contractt_info.URL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.CREATEDBY
     *
     * @return the value of ln_contractt_info.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.CREATEDBY
     *
     * @param createdby the value for ln_contractt_info.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.CREATEDON
     *
     * @return the value of ln_contractt_info.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getCreatedon() {
        return createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.CREATEDON
     *
     * @param createdon the value for ln_contractt_info.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.MODIFIEDBY
     *
     * @return the value of ln_contractt_info.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.MODIFIEDBY
     *
     * @param modifiedby the value for ln_contractt_info.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby == null ? null : modifiedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.MODIFIEDON
     *
     * @return the value of ln_contractt_info.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getModifiedon() {
        return modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.MODIFIEDON
     *
     * @param modifiedon the value for ln_contractt_info.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.VERSION
     *
     * @return the value of ln_contractt_info.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.VERSION
     *
     * @param version the value for ln_contractt_info.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.OSS_ID
     *
     * @return the value of ln_contractt_info.OSS_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getOssId() {
        return ossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.OSS_ID
     *
     * @param ossId the value for ln_contractt_info.OSS_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setOssId(String ossId) {
        this.ossId = ossId == null ? null : ossId.trim();
		if (InputChecker.isEmpty(ossId)) {
			this.ossIdUrl = "";
		} else {
			this.ossIdUrl = OssOpsUtils.getSignUrl(ossId);
		}
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.TEMPLET_OSSID
     *
     * @return the value of ln_contractt_info.TEMPLET_OSSID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getTempletOssid() {
        return templetOssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.TEMPLET_OSSID
     *
     * @param templetOssid the value for ln_contractt_info.TEMPLET_OSSID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setTempletOssid(String templetOssid) {
        this.templetOssid = templetOssid == null ? null : templetOssid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.CONTRACT_CATEGORY
     *
     * @return the value of ln_contractt_info.CONTRACT_CATEGORY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContractCategory() {
        return contractCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.CONTRACT_CATEGORY
     *
     * @param contractCategory the value for ln_contractt_info.CONTRACT_CATEGORY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractCategory(String contractCategory) {
        this.contractCategory = contractCategory == null ? null : contractCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_contractt_info.FIRM_STATUS
     *
     * @return the value of ln_contractt_info.FIRM_STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getFirmStatus() {
        return firmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_contractt_info.FIRM_STATUS
     *
     * @param firmStatus the value for ln_contractt_info.FIRM_STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFirmStatus(String firmStatus) {
        this.firmStatus = firmStatus == null ? null : firmStatus.trim();
    }
    
    public String getOssIdUrl() {
    	 return ossIdUrl;
    }
}