
package com.hm.bus.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-13T18:09:12.565+08:00
 * Generated source version: 3.1.9
 * 
 */
public final class LoanService_LoanServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("microloan", "loanService");

    private LoanService_LoanServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = LoanService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LoanService_Service ss = new LoanService_Service(wsdlURL, SERVICE_NAME);
        LoanService port = ss.getLoanServiceImplPort();  
        
        {
        System.out.println("Invoking updateStatusByAppId...");
        com.hm.bus.webservice.TransHead _updateStatusByAppId_transHead = null;
        BasicOrder _updateStatusByAppId_transBody = null;
        com.hm.bus.webservice.TransModel _updateStatusByAppId__return = port.updateStatusByAppId(_updateStatusByAppId_transHead, _updateStatusByAppId_transBody);
        System.out.println("updateStatusByAppId.result=" + _updateStatusByAppId__return);


        }
        {
        System.out.println("Invoking queryBackTLonApplicationNumber...");
        com.hm.bus.webservice.TransHead _queryBackTLonApplicationNumber_transHead = null;
        String _queryBackTLonApplicationNumber_transBody = "";
        com.hm.bus.webservice.TransModel _queryBackTLonApplicationNumber__return = port.queryBackTLonApplicationNumber(_queryBackTLonApplicationNumber_transHead, _queryBackTLonApplicationNumber_transBody);
        System.out.println("queryBackTLonApplicationNumber.result=" + _queryBackTLonApplicationNumber__return);


        }
        {
        System.out.println("Invoking queryInstToPasService...");
        com.hm.bus.webservice.TransHead _queryInstToPasService_transHead = null;
        com.hm.bus.webservice.PasInst _queryInstToPasService_transBody = null;
        com.hm.bus.webservice.TransModel _queryInstToPasService__return = port.queryInstToPasService(_queryInstToPasService_transHead, _queryInstToPasService_transBody);
        System.out.println("queryInstToPasService.result=" + _queryInstToPasService__return);


        }
        {
        System.out.println("Invoking repRepaySyncCountAll...");
        String _repRepaySyncCountAll_arg0 = "";
        Integer _repRepaySyncCountAll_arg1 = null;
        Integer _repRepaySyncCountAll__return = port.repRepaySyncCountAll(_repRepaySyncCountAll_arg0, _repRepaySyncCountAll_arg1);
        System.out.println("repRepaySyncCountAll.result=" + _repRepaySyncCountAll__return);


        }
        {
        System.out.println("Invoking queryBillAndFactorCount...");
        BillFactCondition _queryBillAndFactorCount_arg0 = null;
        int _queryBillAndFactorCount__return = port.queryBillAndFactorCount(_queryBillAndFactorCount_arg0);
        System.out.println("queryBillAndFactorCount.result=" + _queryBillAndFactorCount__return);


        }
        {
        System.out.println("Invoking findAppIdByNum...");
        String _findAppIdByNum_arg0 = "";
        java.util.List<com.hm.bus.webservice.TLonApplication> _findAppIdByNum__return = port.findAppIdByNum(_findAppIdByNum_arg0);
        System.out.println("findAppIdByNum.result=" + _findAppIdByNum__return);


        }
        {
        System.out.println("Invoking bondValueSyncServiceAll...");
        java.util.List<com.hm.bus.webservice.AppId> _bondValueSyncServiceAll_arg0 = null;
        Integer _bondValueSyncServiceAll_arg1 = null;
        Integer _bondValueSyncServiceAll__return = port.bondValueSyncServiceAll(_bondValueSyncServiceAll_arg0, _bondValueSyncServiceAll_arg1);
        System.out.println("bondValueSyncServiceAll.result=" + _bondValueSyncServiceAll__return);


        }
        {
        System.out.println("Invoking queryMatchRepaymentBatch...");
        String _queryMatchRepaymentBatch_arg0 = "";
        Integer _queryMatchRepaymentBatch_arg1 = null;
        Integer _queryMatchRepaymentBatch_arg2 = null;
        java.util.List<com.hm.bus.webservice.TmatchRepayment> _queryMatchRepaymentBatch__return = port.queryMatchRepaymentBatch(_queryMatchRepaymentBatch_arg0, _queryMatchRepaymentBatch_arg1, _queryMatchRepaymentBatch_arg2);
        System.out.println("queryMatchRepaymentBatch.result=" + _queryMatchRepaymentBatch__return);


        }
        {
        System.out.println("Invoking salesCheckUploadService...");
        com.hm.bus.webservice.TransHead _salesCheckUploadService_transHead = null;
        LoanAttach _salesCheckUploadService_transBody = null;
        com.hm.bus.webservice.TransModel _salesCheckUploadService__return = port.salesCheckUploadService(_salesCheckUploadService_transHead, _salesCheckUploadService_transBody);
        System.out.println("salesCheckUploadService.result=" + _salesCheckUploadService__return);


        }
        {
        System.out.println("Invoking bondValueSyncService...");
        java.util.List<com.hm.bus.webservice.AppId> _bondValueSyncService_arg0 = null;
        Integer _bondValueSyncService_arg1 = null;
        Integer _bondValueSyncService_arg2 = null;
        java.util.List<BondValueSync> _bondValueSyncService__return = port.bondValueSyncService(_bondValueSyncService_arg0, _bondValueSyncService_arg1, _bondValueSyncService_arg2);
        System.out.println("bondValueSyncService.result=" + _bondValueSyncService__return);


        }
        {
        System.out.println("Invoking getWechatCustomer...");
        com.hm.bus.webservice.TransHead _getWechatCustomer_transHead = null;
        com.hm.bus.webservice.WechatCustomerCondition _getWechatCustomer_transBody = null;
        com.hm.bus.webservice.TransModel _getWechatCustomer__return = port.getWechatCustomer(_getWechatCustomer_transHead, _getWechatCustomer_transBody);
        System.out.println("getWechatCustomer.result=" + _getWechatCustomer__return);


        }
        {
        System.out.println("Invoking generateContractForDaNiu...");
        String _generateContractForDaNiu_arg0 = "";
        String _generateContractForDaNiu_arg1 = "";
        String _generateContractForDaNiu_arg2 = "";
        String _generateContractForDaNiu_arg3 = "";
        String _generateContractForDaNiu_arg4 = "";
        String _generateContractForDaNiu__return = port.generateContractForDaNiu(_generateContractForDaNiu_arg0, _generateContractForDaNiu_arg1, _generateContractForDaNiu_arg2, _generateContractForDaNiu_arg3, _generateContractForDaNiu_arg4);
        System.out.println("generateContractForDaNiu.result=" + _generateContractForDaNiu__return);


        }
        {
        System.out.println("Invoking yunDanAttachService...");
        com.hm.bus.webservice.TransHead _yunDanAttachService_transHead = null;
        java.util.List<com.hm.bus.webservice.TLonAttach> _yunDanAttachService_tlonAttachList = null;
        String _yunDanAttachService_appId = "";
        String _yunDanAttachService_saleChannel = "";
        String _yunDanAttachService_productId = "";
        com.hm.bus.webservice.TransModel _yunDanAttachService__return = port.yunDanAttachService(_yunDanAttachService_transHead, _yunDanAttachService_tlonAttachList, _yunDanAttachService_appId, _yunDanAttachService_saleChannel, _yunDanAttachService_productId);
        System.out.println("yunDanAttachService.result=" + _yunDanAttachService__return);


        }
        {
        System.out.println("Invoking queryMatchOrder...");
        com.hm.bus.webservice.TransHead _queryMatchOrder_transHead = null;
        BasicOrder _queryMatchOrder_transBody = null;
        com.hm.bus.webservice.TransModel _queryMatchOrder__return = port.queryMatchOrder(_queryMatchOrder_transHead, _queryMatchOrder_transBody);
        System.out.println("queryMatchOrder.result=" + _queryMatchOrder__return);


        }
        {
        System.out.println("Invoking getBusSeal...");
        String _getBusSeal_arg0 = "";
        String _getBusSeal__return = port.getBusSeal(_getBusSeal_arg0);
        System.out.println("getBusSeal.result=" + _getBusSeal__return);


        }
        {
        System.out.println("Invoking queryNewTLonApplicationNumber...");
        com.hm.bus.webservice.TransHead _queryNewTLonApplicationNumber_transHead = null;
        String _queryNewTLonApplicationNumber_transBody = "";
        com.hm.bus.webservice.TransModel _queryNewTLonApplicationNumber__return = port.queryNewTLonApplicationNumber(_queryNewTLonApplicationNumber_transHead, _queryNewTLonApplicationNumber_transBody);
        System.out.println("queryNewTLonApplicationNumber.result=" + _queryNewTLonApplicationNumber__return);


        }
        {
        System.out.println("Invoking getWXPCCustomer...");
        com.hm.bus.webservice.TransHead _getWXPCCustomer_transHead = null;
        com.hm.bus.webservice.WxpcCustomerCondition _getWXPCCustomer_transBody = null;
        com.hm.bus.webservice.TransModel _getWXPCCustomer__return = port.getWXPCCustomer(_getWXPCCustomer_transHead, _getWXPCCustomer_transBody);
        System.out.println("getWXPCCustomer.result=" + _getWXPCCustomer__return);


        }
        {
        System.out.println("Invoking queryProductToPasService...");
        com.hm.bus.webservice.TransHead _queryProductToPasService_transHead = null;
        com.hm.bus.webservice.PasProduct _queryProductToPasService_transBody = null;
        com.hm.bus.webservice.TransModel _queryProductToPasService__return = port.queryProductToPasService(_queryProductToPasService_transHead, _queryProductToPasService_transBody);
        System.out.println("queryProductToPasService.result=" + _queryProductToPasService__return);


        }
        {
        System.out.println("Invoking matchingAppStatusSyncService...");
        java.util.List<com.hm.bus.webservice.AppId> _matchingAppStatusSyncService_arg0 = null;
        String _matchingAppStatusSyncService__return = port.matchingAppStatusSyncService(_matchingAppStatusSyncService_arg0);
        System.out.println("matchingAppStatusSyncService.result=" + _matchingAppStatusSyncService__return);


        }
        {
        System.out.println("Invoking ysxComService...");
        com.hm.bus.webservice.TransHead _ysxComService_transHead = null;
        com.hm.bus.webservice.YsXinfo _ysxComService_transBody = null;
        com.hm.bus.webservice.TransModel _ysxComService__return = port.ysxComService(_ysxComService_transHead, _ysxComService_transBody);
        System.out.println("ysxComService.result=" + _ysxComService__return);


        }
        {
        System.out.println("Invoking generateRepaymentPlan...");
        Integer _generateRepaymentPlan_arg0 = null;
        String _generateRepaymentPlan__return = port.generateRepaymentPlan(_generateRepaymentPlan_arg0);
        System.out.println("generateRepaymentPlan.result=" + _generateRepaymentPlan__return);


        }
        {
        System.out.println("Invoking doPreCreditLimiteQuery...");
        com.hm.bus.webservice.TransHead _doPreCreditLimiteQuery_transHead = null;
        com.hm.bus.webservice.UserInfo58 _doPreCreditLimiteQuery_transBody = null;
        com.hm.bus.webservice.TransModel _doPreCreditLimiteQuery__return = port.doPreCreditLimiteQuery(_doPreCreditLimiteQuery_transHead, _doPreCreditLimiteQuery_transBody);
        System.out.println("doPreCreditLimiteQuery.result=" + _doPreCreditLimiteQuery__return);


        }
        {
        System.out.println("Invoking doPeriodAppRecive...");
        com.hm.bus.webservice.TransHead _doPeriodAppRecive_transHead = null;
        Contract58 _doPeriodAppRecive_transBody = null;
        com.hm.bus.webservice.TransModel _doPeriodAppRecive__return = port.doPeriodAppRecive(_doPeriodAppRecive_transHead, _doPeriodAppRecive_transBody);
        System.out.println("doPeriodAppRecive.result=" + _doPeriodAppRecive__return);


        }
        {
        System.out.println("Invoking queryMatchRepayment...");
        com.hm.bus.webservice.TransHead _queryMatchRepayment_transHead = null;
        com.hm.bus.webservice.TmatchAppId _queryMatchRepayment_transBody = null;
        com.hm.bus.webservice.TransModel _queryMatchRepayment__return = port.queryMatchRepayment(_queryMatchRepayment_transHead, _queryMatchRepayment_transBody);
        System.out.println("queryMatchRepayment.result=" + _queryMatchRepayment__return);


        }
        {
        System.out.println("Invoking getYanZheng...");
        String _getYanZheng_arg0 = "";
        String _getYanZheng__return = port.getYanZheng(_getYanZheng_arg0);
        System.out.println("getYanZheng.result=" + _getYanZheng__return);


        }
        {
        System.out.println("Invoking ysxAttachService...");
        com.hm.bus.webservice.TransHead _ysxAttachService_arg0 = null;
        com.hm.bus.webservice.WebYsxAttach _ysxAttachService_arg1 = null;
        com.hm.bus.webservice.TransModel _ysxAttachService__return = port.ysxAttachService(_ysxAttachService_arg0, _ysxAttachService_arg1);
        System.out.println("ysxAttachService.result=" + _ysxAttachService__return);


        }
        {
        System.out.println("Invoking findAppIdByNums...");
        com.hm.bus.webservice.TransHead _findAppIdByNums_arg0 = null;
        String _findAppIdByNums_arg1 = "";
        com.hm.bus.webservice.TransModel _findAppIdByNums__return = port.findAppIdByNums(_findAppIdByNums_arg0, _findAppIdByNums_arg1);
        System.out.println("findAppIdByNums.result=" + _findAppIdByNums__return);


        }
        {
        System.out.println("Invoking generateContract...");
        String _generateContract_arg0 = "";
        String _generateContract__return = port.generateContract(_generateContract_arg0);
        System.out.println("generateContract.result=" + _generateContract__return);


        }
        {
        System.out.println("Invoking seeContract...");
        String _seeContract_arg0 = "";
        String _seeContract__return = port.seeContract(_seeContract_arg0);
        System.out.println("seeContract.result=" + _seeContract__return);


        }
        {
        System.out.println("Invoking credSynch...");
        com.hm.bus.webservice.TransHead _credSynch_transHead = null;
        BasicOrder _credSynch_transBody = null;
        com.hm.bus.webservice.TransModel _credSynch__return = port.credSynch(_credSynch_transHead, _credSynch_transBody);
        System.out.println("credSynch.result=" + _credSynch__return);


        }
        {
        System.out.println("Invoking doPreAuditAppGet...");
        com.hm.bus.webservice.TransHead _doPreAuditAppGet_transHead = null;
        com.hm.bus.webservice.TLoanAppInstallments _doPreAuditAppGet_transBody = null;
        com.hm.bus.webservice.TransModel _doPreAuditAppGet__return = port.doPreAuditAppGet(_doPreAuditAppGet_transHead, _doPreAuditAppGet_transBody);
        System.out.println("doPreAuditAppGet.result=" + _doPreAuditAppGet__return);


        }
        {
        System.out.println("Invoking recordLoanAttachService...");
        com.hm.bus.webservice.TransHead _recordLoanAttachService_transHead = null;
        LoanAttach _recordLoanAttachService_transBody = null;
        com.hm.bus.webservice.TransModel _recordLoanAttachService__return = port.recordLoanAttachService(_recordLoanAttachService_transHead, _recordLoanAttachService_transBody);
        System.out.println("recordLoanAttachService.result=" + _recordLoanAttachService__return);


        }
        {
        System.out.println("Invoking updateProcess...");
        com.hm.bus.webservice.TransHead _updateProcess_transHead = null;
        com.hm.bus.webservice.TLonApplication _updateProcess_transBody = null;
        com.hm.bus.webservice.TransModel _updateProcess__return = port.updateProcess(_updateProcess_transHead, _updateProcess_transBody);
        System.out.println("updateProcess.result=" + _updateProcess__return);


        }
        {
        System.out.println("Invoking queryOrder...");
        com.hm.bus.webservice.TransHead _queryOrder_transHead = null;
        BasicOrder _queryOrder_transBody = null;
        com.hm.bus.webservice.TransModel _queryOrder__return = port.queryOrder(_queryOrder_transHead, _queryOrder_transBody);
        System.out.println("queryOrder.result=" + _queryOrder__return);


        }
        {
        System.out.println("Invoking recordLoan...");
        com.hm.bus.webservice.TransHead _recordLoan_transHead = null;
        com.hm.bus.webservice.LonApp _recordLoan_transBody = null;
        com.hm.bus.webservice.TransModel _recordLoan__return = port.recordLoan(_recordLoan_transHead, _recordLoan_transBody);
        System.out.println("recordLoan.result=" + _recordLoan__return);


        }
        {
        System.out.println("Invoking overduePaymentFeedback...");
        com.hm.bus.webservice.TransHead _overduePaymentFeedback_transHead = null;
        com.hm.bus.webservice.OverduePaymentBean _overduePaymentFeedback_transBody = null;
        com.hm.bus.webservice.TransModel _overduePaymentFeedback__return = port.overduePaymentFeedback(_overduePaymentFeedback_transHead, _overduePaymentFeedback_transBody);
        System.out.println("overduePaymentFeedback.result=" + _overduePaymentFeedback__return);


        }
        {
        System.out.println("Invoking appStatusFeedback...");
        com.hm.bus.webservice.TransHead _appStatusFeedback_transHead = null;
        AppStatusBean _appStatusFeedback_transBody = null;
        com.hm.bus.webservice.TransModel _appStatusFeedback__return = port.appStatusFeedback(_appStatusFeedback_transHead, _appStatusFeedback_transBody);
        System.out.println("appStatusFeedback.result=" + _appStatusFeedback__return);


        }
        {
        System.out.println("Invoking doPreAuditAppRecive...");
        com.hm.bus.webservice.TransHead _doPreAuditAppRecive_transHead = null;
        com.hm.bus.webservice.TLoanApp58 _doPreAuditAppRecive_transBody = null;
        com.hm.bus.webservice.TransModel _doPreAuditAppRecive__return = port.doPreAuditAppRecive(_doPreAuditAppRecive_transHead, _doPreAuditAppRecive_transBody);
        System.out.println("doPreAuditAppRecive.result=" + _doPreAuditAppRecive__return);


        }
        {
        System.out.println("Invoking realRepaySyncCountAll...");
        String _realRepaySyncCountAll_arg0 = "";
        Integer _realRepaySyncCountAll_arg1 = null;
        Integer _realRepaySyncCountAll__return = port.realRepaySyncCountAll(_realRepaySyncCountAll_arg0, _realRepaySyncCountAll_arg1);
        System.out.println("realRepaySyncCountAll.result=" + _realRepaySyncCountAll__return);


        }
        {
        System.out.println("Invoking saveLatentCustomerService...");
        com.hm.bus.webservice.TransHead _saveLatentCustomerService_transHead = null;
        com.hm.bus.webservice.TLatentCustomer _saveLatentCustomerService_transBody = null;
        com.hm.bus.webservice.TransModel _saveLatentCustomerService__return = port.saveLatentCustomerService(_saveLatentCustomerService_transHead, _saveLatentCustomerService_transBody);
        System.out.println("saveLatentCustomerService.result=" + _saveLatentCustomerService__return);


        }
        {
        System.out.println("Invoking doRePaymentQuery...");
        com.hm.bus.webservice.TransHead _doRePaymentQuery_transHead = null;
        com.hm.bus.webservice.Repayment58 _doRePaymentQuery_transBody = null;
        com.hm.bus.webservice.TransModel _doRePaymentQuery__return = port.doRePaymentQuery(_doRePaymentQuery_transHead, _doRePaymentQuery_transBody);
        System.out.println("doRePaymentQuery.result=" + _doRePaymentQuery__return);


        }
        {
        System.out.println("Invoking queryLoanToPasService...");
        com.hm.bus.webservice.TransHead _queryLoanToPasService_transHead = null;
        com.hm.bus.webservice.PasLoan _queryLoanToPasService_transBody = null;
        com.hm.bus.webservice.TransModel _queryLoanToPasService__return = port.queryLoanToPasService(_queryLoanToPasService_transHead, _queryLoanToPasService_transBody);
        System.out.println("queryLoanToPasService.result=" + _queryLoanToPasService__return);


        }
        {
        System.out.println("Invoking doPreAuditAppCheck...");
        com.hm.bus.webservice.TransHead _doPreAuditAppCheck_transHead = null;
        InstallmentGoCheckEntity _doPreAuditAppCheck_transBody = null;
        com.hm.bus.webservice.TransModel _doPreAuditAppCheck__return = port.doPreAuditAppCheck(_doPreAuditAppCheck_transHead, _doPreAuditAppCheck_transBody);
        System.out.println("doPreAuditAppCheck.result=" + _doPreAuditAppCheck__return);


        }
        {
        System.out.println("Invoking updateContract...");
        com.hm.bus.webservice.TransHead _updateContract_transHead = null;
        com.hm.bus.webservice.TLonApplicationContract _updateContract_transBody = null;
        com.hm.bus.webservice.TransModel _updateContract__return = port.updateContract(_updateContract_transHead, _updateContract_transBody);
        System.out.println("updateContract.result=" + _updateContract__return);


        }
        {
        System.out.println("Invoking checkYanZheng...");
        String _checkYanZheng_arg0 = "";
        String _checkYanZheng_arg1 = "";
        String _checkYanZheng__return = port.checkYanZheng(_checkYanZheng_arg0, _checkYanZheng_arg1);
        System.out.println("checkYanZheng.result=" + _checkYanZheng__return);


        }
        {
        System.out.println("Invoking haveLendAppSyncService...");
        String _haveLendAppSyncService_arg0 = "";
        java.util.List<com.hm.bus.webservice.MatchingAppSync> _haveLendAppSyncService__return = port.haveLendAppSyncService(_haveLendAppSyncService_arg0);
        System.out.println("haveLendAppSyncService.result=" + _haveLendAppSyncService__return);


        }
        {
        System.out.println("Invoking accountAndSignLoan...");
        com.hm.bus.webservice.TransHead _accountAndSignLoan_transHead = null;
        ContractBean _accountAndSignLoan_transBody = null;
        com.hm.bus.webservice.TransModel _accountAndSignLoan__return = port.accountAndSignLoan(_accountAndSignLoan_transHead, _accountAndSignLoan_transBody);
        System.out.println("accountAndSignLoan.result=" + _accountAndSignLoan__return);


        }
        {
        System.out.println("Invoking calculateBonds...");
        com.hm.bus.webservice.TransHead _calculateBonds_transHead = null;
        com.hm.bus.webservice.TApplicationBody _calculateBonds_transBody = null;
        com.hm.bus.webservice.TransModel _calculateBonds__return = port.calculateBonds(_calculateBonds_transHead, _calculateBonds_transBody);
        System.out.println("calculateBonds.result=" + _calculateBonds__return);


        }
        {
        System.out.println("Invoking fullScaleAppSyncService...");
        java.util.List<com.hm.bus.webservice.AppId> _fullScaleAppSyncService_arg0 = null;
        java.util.List<String> _fullScaleAppSyncService__return = port.fullScaleAppSyncService(_fullScaleAppSyncService_arg0);
        System.out.println("fullScaleAppSyncService.result=" + _fullScaleAppSyncService__return);


        }
        {
        System.out.println("Invoking payPlayStatusFeedback...");
        com.hm.bus.webservice.TransHead _payPlayStatusFeedback_transHead = null;
        com.hm.bus.webservice.PayPlanRequestBean _payPlayStatusFeedback_transBody = null;
        com.hm.bus.webservice.TransModel _payPlayStatusFeedback__return = port.payPlayStatusFeedback(_payPlayStatusFeedback_transHead, _payPlayStatusFeedback_transBody);
        System.out.println("payPlayStatusFeedback.result=" + _payPlayStatusFeedback__return);


        }
        {
        System.out.println("Invoking getLoanStatus...");
        com.hm.bus.webservice.TransHead _getLoanStatus_transHead = null;
        com.hm.bus.webservice.StatusCondition _getLoanStatus_transBody = null;
        com.hm.bus.webservice.TransModel _getLoanStatus__return = port.getLoanStatus(_getLoanStatus_transHead, _getLoanStatus_transBody);
        System.out.println("getLoanStatus.result=" + _getLoanStatus__return);


        }
        {
        System.out.println("Invoking updateTLonUserkh...");
        com.hm.bus.webservice.TransHead _updateTLonUserkh_transHead = null;
        com.hm.bus.webservice.TLonUserkh _updateTLonUserkh_transBody = null;
        com.hm.bus.webservice.TransModel _updateTLonUserkh__return = port.updateTLonUserkh(_updateTLonUserkh_transHead, _updateTLonUserkh_transBody);
        System.out.println("updateTLonUserkh.result=" + _updateTLonUserkh__return);


        }
        {
        System.out.println("Invoking validateCoustmor...");
        com.hm.bus.webservice.TransHead _validateCoustmor_transHead = null;
        com.hm.bus.webservice.ValidateMap _validateCoustmor_transBody = null;
        com.hm.bus.webservice.TransModel _validateCoustmor__return = port.validateCoustmor(_validateCoustmor_transHead, _validateCoustmor_transBody);
        System.out.println("validateCoustmor.result=" + _validateCoustmor__return);


        }
        {
        System.out.println("Invoking syncRepaymentInfos...");
        String _syncRepaymentInfos_arg0 = "";
        java.util.List<com.hm.bus.webservice.RePaymentWebServiceModel> _syncRepaymentInfos__return = port.syncRepaymentInfos(_syncRepaymentInfos_arg0);
        System.out.println("syncRepaymentInfos.result=" + _syncRepaymentInfos__return);


        }
        {
        System.out.println("Invoking queryBillAndFactoringInfo...");
        BillFactCondition _queryBillAndFactoringInfo_arg0 = null;
        java.util.List<BillAndFactoring> _queryBillAndFactoringInfo__return = port.queryBillAndFactoringInfo(_queryBillAndFactoringInfo_arg0);
        System.out.println("queryBillAndFactoringInfo.result=" + _queryBillAndFactoringInfo__return);


        }
        {
        System.out.println("Invoking doVehicleRecive...");
        com.hm.bus.webservice.TransHead _doVehicleRecive_transHead = null;
        CarInfo58 _doVehicleRecive_transBody = null;
        com.hm.bus.webservice.TransModel _doVehicleRecive__return = port.doVehicleRecive(_doVehicleRecive_transHead, _doVehicleRecive_transBody);
        System.out.println("doVehicleRecive.result=" + _doVehicleRecive__return);


        }
        {
        System.out.println("Invoking doGetFundApply...");
        com.hm.bus.webservice.TransHead _doGetFundApply_transHead = null;
        com.hm.bus.webservice.Payment58 _doGetFundApply_transBody = null;
        com.hm.bus.webservice.TransModel _doGetFundApply__return = port.doGetFundApply(_doGetFundApply_transHead, _doGetFundApply_transBody);
        System.out.println("doGetFundApply.result=" + _doGetFundApply__return);


        }
        {
        System.out.println("Invoking getMatchRelation...");
        com.hm.bus.webservice.TransHead _getMatchRelation_transHead = null;
        com.hm.bus.webservice.LonAppPayXML _getMatchRelation_transBody = null;
        com.hm.bus.webservice.TransModel _getMatchRelation__return = port.getMatchRelation(_getMatchRelation_transHead, _getMatchRelation_transBody);
        System.out.println("getMatchRelation.result=" + _getMatchRelation__return);


        }
        {
        System.out.println("Invoking matchingAppSyncService...");
        String _matchingAppSyncService_arg0 = "";
        java.util.List<com.hm.bus.webservice.MatchingAppSync> _matchingAppSyncService__return = port.matchingAppSyncService(_matchingAppSyncService_arg0);
        System.out.println("matchingAppSyncService.result=" + _matchingAppSyncService__return);


        }
        {
        System.out.println("Invoking doGetMortgagorList...");
        com.hm.bus.webservice.TransHead _doGetMortgagorList_transHead = null;
        com.hm.bus.webservice.TLoanAppInstallments _doGetMortgagorList_transBody = null;
        com.hm.bus.webservice.TransModel _doGetMortgagorList__return = port.doGetMortgagorList(_doGetMortgagorList_transHead, _doGetMortgagorList_transBody);
        System.out.println("doGetMortgagorList.result=" + _doGetMortgagorList__return);


        }
        {
        System.out.println("Invoking getWechatContractAlgorithm...");
        com.hm.bus.webservice.TransHead _getWechatContractAlgorithm_transHead = null;
        ContractCondition _getWechatContractAlgorithm_transBody = null;
        com.hm.bus.webservice.TransModel _getWechatContractAlgorithm__return = port.getWechatContractAlgorithm(_getWechatContractAlgorithm_transHead, _getWechatContractAlgorithm_transBody);
        System.out.println("getWechatContractAlgorithm.result=" + _getWechatContractAlgorithm__return);


        }
        {
        System.out.println("Invoking queryRepayment...");
        com.hm.bus.webservice.TransHead _queryRepayment_transHead = null;
        String _queryRepayment_transBody = "";
        com.hm.bus.webservice.TransModel _queryRepayment__return = port.queryRepayment(_queryRepayment_transHead, _queryRepayment_transBody);
        System.out.println("queryRepayment.result=" + _queryRepayment__return);


        }
        {
        System.out.println("Invoking realRepaySyncService...");
        String _realRepaySyncService_arg0 = "";
        Integer _realRepaySyncService_arg1 = null;
        Integer _realRepaySyncService_arg2 = null;
        java.util.List<com.hm.bus.webservice.RealRepaySync> _realRepaySyncService__return = port.realRepaySyncService(_realRepaySyncService_arg0, _realRepaySyncService_arg1, _realRepaySyncService_arg2);
        System.out.println("realRepaySyncService.result=" + _realRepaySyncService__return);


        }

        System.exit(0);
    }

}
