package com.times.acs.pojo.admin;

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

// Generated 2012-4-10 22:41:15 by Hibernate Tools 3.4.0.CR1

/**
 * RoleHqlcondition generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true, value = { "hibernateLazyInitializer"})
public class RoleHqlcondition implements java.io.Serializable {

	private Long id;
	private String entityName;
	private Long roleId;
	private String caption;
	private Integer parentid;
	private String fieldName;
	private String operator;
	private String paramName;

	private String joinWord;
	private String paramValue;
	private String roleName;
	private String roleCode;

	
	public String getRoleCode() {
		return roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public Set<RoleHqlcondition> getChilds() {
		return childs;
	}

	public void setChilds(Set<RoleHqlcondition> childs) {
		this.childs = childs;
	}

	private String fldType;

	private Set<RoleHqlcondition> childs = new HashSet<RoleHqlcondition>(0);

	public RoleHqlcondition() {
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public RoleHqlcondition(String entityName, Long roleId, String caption,
			Integer parentid, String fieldName, String operator,
			String paramName, String joinWord, String paramValue) {
		this.entityName = entityName;
		this.roleId = roleId;
		this.caption = caption;
		this.parentid = parentid;
		this.fieldName = fieldName;
		this.operator = operator;
		this.paramName = paramName;
		this.joinWord = joinWord;
		this.paramValue = paramValue;
	}

	public Long getId() {
		return this.id;
	}

	public String getFldType() {
		return fldType;
	}

	public void setFldType(String fldType) {
		this.fldType = fldType;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEntityName() {
		return entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public String getJoinWord() {
		return this.joinWord;
	}

	public void setJoinWord(String joinWord) {
		this.joinWord = joinWord;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

}
