package com.times.acs.pojo.admin;

// Generated 2012-3-7 18:21:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Version;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * SmArtical generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(ignoreUnknown = true, value = { "hibernateLazyInitializer" })
public class SmApplication implements java.io.Serializable {

	@Id
	@GeneratedValue
	private Long id;
	@Version
	private Integer version;
	/**
	 * 应用编码
	 */
	private String code;

	/**
	 * 应用名称
	 */
	private String name;

	private String createBy;
	private String modifyBy;
	private Date modifyOn;
	private Date createOn;
	private String packageName;

	public String getPackageName() {
		return packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	/**
	 * 应用地址
	 */
	private String url;

	/**
	 * 应用介绍
	 */
	private String introduction;

	/**
	 * 应用图标
	 */
	private String icon;

	private Integer smSystemType;
	private Integer displaydb;
	private Integer isApplicants;

	public Integer getSmSystemType() {
		return smSystemType;
	}

	public void setSmSystemType(Integer smSystemType) {
		this.smSystemType = smSystemType;
	}

	public Integer getDisplaydb() {
		return displaydb;
	}

	public void setDisplaydb(Integer displaydb) {
		this.displaydb = displaydb;
	}

	public String getIntroduction() {
		return introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public SmApplication() {
	}

	public SmApplication(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public SmApplication(String code, String name, String createBy,
			String modifyBy, Date modifyOn, Date createOn) {
		super();
		this.code = code;
		this.name = name;
		this.createBy = createBy;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
		this.createOn = createOn;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public Date getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	public Integer getIsApplicants() {
		return isApplicants;
	}

	public void setIsApplicants(Integer isApplicants) {
		this.isApplicants = isApplicants;
	}
	
}
