package com.times.acs.pojo.admin;

// Generated 2012-3-1 18:50:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * 
 * SmLog generated by hbm2java
 * 
 * 
 * 记录系统日志，类型为一般日志和审计日志
 * 
 * 
 */
@JsonIgnoreProperties(ignoreUnknown = true, value = { "hibernateLazyInitializer"})
public class SmLog implements java.io.Serializable {

//	public static String LOG_COMMON = "一般日志";
//
//	public static String LOG_AUDIT = "审计日志";

	public static String LOG_AUDIT_RESULT_SUCCESS = "成功";

	public static String LOG_AUDIT_RESULT_FAILED = "失败";

	public static String LOG_AUDIT_TYPE_ADMIN_OPS = "系统管理员操作日志";

	public static String LOG_AUDIT_TYPE_SECURITY_OFFICER_OPS = "安全保密员操作日志";

	public static String LOG_AUDIT_TYPE_AUDITOR_OPS = "安全审计员操作日志";
	
	public static String LOG_AUDIT_TYPE_BIZ_OPS = "业务用户操作日志";

	public static String LOG_AUDIT_TYPE_AUDIT_DATA_OPS = "涉密数据操作";

	public static String LOG_AUDIT_TYPE_ACCESS_VALIDATOR = "身份鉴别";
	
	public static String LOG_AUDIT_TYPE_NOACCESS = "无授权访问";
	
	public static String LOG_AUDIT_TYPE_INFORMODIFY = "涉密信息被篡改";

	public static String LOG_AUDIT_TYPE_OTHER = "其它";

	public static String LOG_AUDIT_SECRET = "秘密";

	public static String LOG_AUDIT_CONFIDENTIAL = "机密";

	public static String LOG_AUDIT_NOSECRET = "非密";

	public static String SECRETTYPE_NO = "no";
	
	//ADD NEW
	public static Integer OPERTYPE_ADD = 1;//操作类型：添加
	
	public static Integer OPERTYPE_DELETE = 2;//操作类型：删除
	
	public static Integer OPERTYPE_QUERY = 3;//操作类型：查看
	
	public static Integer OPERTYPE_MODIFY = 4;//操作类型：修改
	
	public static Integer OPERTYPE_LOGIN = 5;//操作类型：登录
	
	public static String LOGTYPE_BIZUSER = "1";// TYPE：业务用户操作日志
	
	public static String LOGTYPE_AUDITOR = "2";// TYPE：安全审计员操作日志
	
	public static String LOGTYPE_SECURITY = "3";// TYPE：安全保密员操作日志
	
	public static String LOGTYPE_ADMIN = "4";// TYPE：系统管理员操作日志
	

	
	public static String LOGTYPE_OTHER = "5";// TYPE：其他（如涉密信息被篡改）
	
	public static String LOGTYPE_NOLOGIN = "6";// TYPE：匿名用户访问

	/**
	 * 秘密类型
	 */
	public static String SECRETTYPE_SECRET = RolesPOJO.SECRET_ROLE;

	/**
	 * 机密类型
	 */
	public static String SECRETTYPE_CONFIDENTIAL = RolesPOJO.CONFIDENTIAL_ROLE;

	private Long id;
	
	/**
	 * 登录的用户名称
	 */
	private String loginName;
	
	
	/**
	 * 登录的ip地址
	 */
	private String loginIp;
	/**
	 * 模块名称
	 */
	private String moduleName;
	/**
	 * 记录内容
	 */
	private String logContent;

	/**
	 * 记录日期
	 */
	private Date logDate;

	/**
	 * 请求到达服务器的时间
	 */
	private Date requestStartTime;

	/**
	 * 请求结束事件
	 */
	private Date requestEndTime;

	/**
	 * 系统处理请求用时
	 */
	private Long systemDealTime;
	/**
	 * 日志类型
	 * 
	 * 审计日志，一般日志
	 */
	private String type;

	/**
	 * 日志子类型 审计日志：
	 * 
	 * 身份鉴别， 访问控制 系统管理员操作， 安全保密管理员操作， 安全审计员操作， 涉密数据操作 其他可以审计的事件类型
	 * 
	 */
	private String subType;

	/**
	 * 操作的结果： 成功，失败
	 */
	private String result;

	// private Date startTime;
	// private long runTimes;
	private Integer moduleType;//模块类别，jjcode定义
	private Integer operType; //操作类别，jjcode中定义 新建，修改，删除，登录
	private String logTitle; //日志标题
	private String md5Value;
	private SmLogDataVO dataVO;//用于存储内容
	/**
	 * 记录内容（用于显示）
	 */
	private String logContentView;
	
	private Long orgId;
	
	private String  url;
	
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getType() {
		return type;
	}

	public Date getRequestStartTime() {
		return requestStartTime;
	}

	public void setRequestStartTime(Date requestStartTime) {
		this.requestStartTime = requestStartTime;
	}

	public Date getRequestEndTime() {
		return requestEndTime;
	}

	public void setRequestEndTime(Date requestEndTime) {
		this.requestEndTime = requestEndTime;
	}

	public Long getSystemDealTime() {
		if (requestStartTime != null && requestEndTime != null) {
			return requestEndTime.getTime() - requestStartTime.getTime();
		}
		return systemDealTime;
	}

	public void setSystemDealTime(Long systemDealTime) {
		this.systemDealTime = systemDealTime;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSubType() {
		return subType;
	}

	public void setSubType(String subType) {
		this.subType = subType;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public SmLog() {
	}

	public SmLog(String loginName, String loginIp, String moduleName,
			String logContent, Date logDate) {
		this.loginName = loginName;
		this.loginIp = loginIp;
		this.moduleName = moduleName;
		this.logContent = logContent;
		this.logDate = logDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	public String getLogContent() {
		return this.logContent;
	}

	public void setLogContent(String logContent) {
		this.logContent = logContent;
	}

	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	/**
	 * 所属应用程序编码
	 */
	private String appCode;

	public String getAppCode() {
		return appCode;
	}

	public void setAppCode(String appCode) {
		this.appCode = appCode;
	}

	public Integer getModuleType() {
		return moduleType;
	}

	public void setModuleType(Integer moduleType) {
		this.moduleType = moduleType;
	}

	public Integer getOperType() {
		return operType;
	}

	public void setOperType(Integer operType) {
		this.operType = operType;
	}

	public String getLogTitle() {
		return logTitle;
	}

	public void setLogTitle(String logTitle) {
		this.logTitle = logTitle;
	}

	public String getMd5Value() {
		return md5Value;
	}

	public void setMd5Value(String md5Value) {
		this.md5Value = md5Value;
	}

	public SmLogDataVO getDataVO() {
		return dataVO;
	}

	public void setDataVO(SmLogDataVO dataVO) {
		this.dataVO = dataVO;
	}

	public String getLogContentView() {
		return logContentView;
	}

	public void setLogContentView(String logContentView) {
		this.logContentView = logContentView;
	}

	public Long getOrgId() {
		return orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

}
