package com.times.acs.pojo.admin;

// Generated 2013-11-19 9:40:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * SmNotice generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true, value = { "hibernateLazyInitializer"})
public class SmNotice implements java.io.Serializable {

	private Long id;
	private Long receiveId;
	private String receiveName;
	private Integer moduleId;
	private String ntTitle;
	private String ntContent;
	private Long receiveOrgId;
	private Long receiveDeptId;
	private String receiveDeptName;
	private Integer ntType;
	private Long sendId;
	private String sendName;
	private Date receveTime;
	private Integer readStatus;
	private Date readTime;
	private Integer delStatus;
	private Integer zhdStatus;
	private Integer emegStatus;
	private String showColor;
	private Date showEndTime;
	private Integer showStatus;
	private String linkPage;
	private String linkUrl;

	/**
	 * 模块定义
	 */
	public static final int  MODULE_USERMANAGER=1;
	public SmNotice() {
		
	}
	
	//系统发送消息用
	public SmNotice(Long receiveId, String receiveName, Integer moduleId,
			String ntTitle, String ntContent, Long receiveOrgId,
			Long receiveDeptId, String receiveDeptName, String linkPage) {
		this.receiveId = receiveId;
		this.receiveName = receiveName;
		this.moduleId = moduleId;
		this.ntTitle = ntTitle;
		this.ntContent = ntContent;
		this.receiveOrgId = receiveOrgId;
		this.receiveDeptId = receiveDeptId;
		this.receiveDeptName = receiveDeptName;
		this.sendName="系统";
		this.receveTime=new Date();
		this.ntType = 1;
		this.readStatus = 0;
		this.delStatus = 0;
		
		this.linkPage = linkPage;
		
	}
	public SmNotice(Long receiveId, String receiveName, Integer moduleId,
			String ntTitle, String ntContent, Long receiveOrgId,
			Long receiveDeptId, String receiveDeptName, Integer ntType,
			Long sendId, String sendName, Date receveTime, Integer readStatus,
			Date readTime, Integer delStatus, Integer zhdStatus,
			Integer emegStatus, String showColor, Date showEndTime,
			Integer showStatus, String linkPage, String linkUrl) {
		this.receiveId = receiveId;
		this.receiveName = receiveName;
		this.moduleId = moduleId;
		this.ntTitle = ntTitle;
		this.ntContent = ntContent;
		this.receiveOrgId = receiveOrgId;
		this.receiveDeptId = receiveDeptId;
		this.receiveDeptName = receiveDeptName;
		this.ntType = ntType;
		this.sendId = sendId;
		this.sendName = sendName;
		this.receveTime = receveTime;
		this.readStatus = readStatus;
		this.readTime = readTime;
		this.delStatus = delStatus;
		this.zhdStatus = zhdStatus;
		this.emegStatus = emegStatus;
		this.showColor = showColor;
		this.showEndTime = showEndTime;
		this.showStatus = showStatus;
		this.linkPage = linkPage;
		this.linkUrl = linkUrl;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(Long receiveId) {
		this.receiveId = receiveId;
	}

	public String getReceiveName() {
		return this.receiveName;
	}

	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	public String getNtTitle() {
		return this.ntTitle;
	}

	public void setNtTitle(String ntTitle) {
		this.ntTitle = ntTitle;
	}

	public String getNtContent() {
		return this.ntContent;
	}

	public void setNtContent(String ntContent) {
		this.ntContent = ntContent;
	}

	public Long getReceiveOrgId() {
		return this.receiveOrgId;
	}

	public void setReceiveOrgId(Long receiveOrgId) {
		this.receiveOrgId = receiveOrgId;
	}

	public Long getReceiveDeptId() {
		return this.receiveDeptId;
	}

	public void setReceiveDeptId(Long receiveDeptId) {
		this.receiveDeptId = receiveDeptId;
	}

	public String getReceiveDeptName() {
		return this.receiveDeptName;
	}

	public void setReceiveDeptName(String receiveDeptName) {
		this.receiveDeptName = receiveDeptName;
	}

	public Integer getNtType() {
		return this.ntType;
	}

	public void setNtType(Integer ntType) {
		this.ntType = ntType;
	}

	public Long getSendId() {
		return this.sendId;
	}

	public void setSendId(Long sendId) {
		this.sendId = sendId;
	}

	public String getSendName() {
		return this.sendName;
	}

	public void setSendName(String sendName) {
		this.sendName = sendName;
	}

	public Date getReceveTime() {
		return this.receveTime;
	}

	public void setReceveTime(Date receveTime) {
		this.receveTime = receveTime;
	}

	public Integer getReadStatus() {
		return this.readStatus;
	}

	public void setReadStatus(Integer readStatus) {
		this.readStatus = readStatus;
	}

	public Date getReadTime() {
		return this.readTime;
	}

	public void setReadTime(Date readTime) {
		this.readTime = readTime;
	}

	public Integer getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(Integer delStatus) {
		this.delStatus = delStatus;
	}

	public Integer getZhdStatus() {
		return this.zhdStatus;
	}

	public void setZhdStatus(Integer zhdStatus) {
		this.zhdStatus = zhdStatus;
	}

	public Integer getEmegStatus() {
		return this.emegStatus;
	}

	public void setEmegStatus(Integer emegStatus) {
		this.emegStatus = emegStatus;
	}

	public String getShowColor() {
		return this.showColor;
	}

	public void setShowColor(String showColor) {
		this.showColor = showColor;
	}

	public Date getShowEndTime() {
		return this.showEndTime;
	}

	public void setShowEndTime(Date showEndTime) {
		this.showEndTime = showEndTime;
	}

	public Integer getShowStatus() {
		return this.showStatus;
	}

	public void setShowStatus(Integer showStatus) {
		this.showStatus = showStatus;
	}

	public String getLinkPage() {
		return this.linkPage;
	}

	public void setLinkPage(String linkPage) {
		this.linkPage = linkPage;
	}

	public String getLinkUrl() {
		return this.linkUrl;
	}

	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

}
