package com.times.acs.pojo.admin;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

// Generated 2013-7-13 15:55:33 by Hibernate Tools 3.4.0.CR1

/**
 * UserGroupMapping generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true, value = { "dn",
	    "hibernateLazyInitializer", "handler" })
public class UserGroupMapping implements java.io.Serializable {

	/**
	 * 内网机构中代表司局机构的类型
	 */
	
	public static final String JG_SJ ="2";
	private Long id;
	private String jgId;
	private String sjjgId;
	private String jgMc;
	private String ccm;
	private Integer seq;

	public UserGroupMapping() {
	}

	public UserGroupMapping(String jgId) {
		this.jgId = jgId;
	}

	public UserGroupMapping(String jgId, String sjjgId, String jgMc,
			String ccm, Integer seq) {
		this.jgId = jgId;
		this.sjjgId = sjjgId;
		this.jgMc = jgMc;
		this.ccm = ccm;
		this.seq = seq;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getJgId() {
		return this.jgId;
	}

	public void setJgId(String jgId) {
		this.jgId = jgId;
	}

	public String getSjjgId() {
		return this.sjjgId;
	}

	public void setSjjgId(String sjjgId) {
		this.sjjgId = sjjgId;
	}

	public String getJgMc() {
		return this.jgMc;
	}

	public void setJgMc(String jgMc) {
		this.jgMc = jgMc;
	}

	public String getCcm() {
		return this.ccm;
	}

	public void setCcm(String ccm) {
		this.ccm = ccm;
	}

	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

}
