package com.times.acs.pojo.admin;

// Generated 2012-8-14 14:53:28 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * UserMsg generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true, value = { "hibernateLazyInitializer"})
public class UserMsg implements java.io.Serializable {

	private Long msgId;
	private Integer version;
	private String sender;
	private String receiver;
	private Integer msgStatus;
	private Date senderTime;
	private Boolean isRead;
	private Date readTime;
	private String msgContent;
	private String createBy;
	private String modifyBy;
	private Date modifyOn;
	private Date createOn;

	public UserMsg() {
	}

	public UserMsg(String sender, String receiver) {
		this.sender = sender;
		this.receiver = receiver;
	}

	public UserMsg(String senderId, String receiverId, Integer msgStatus,
			Date senderTime, Boolean isRead, Date readTime, String msgContent,
			String createBy, String modifyBy, Date modifyOn, Date createOn) {
		this.sender = senderId;
		this.receiver = receiverId;
		this.msgStatus = msgStatus;
		this.senderTime = senderTime;
		this.isRead = isRead;
		this.readTime = readTime;
		this.msgContent = msgContent;
		this.createBy = createBy;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
		this.createOn = createOn;
	}

	public Long getMsgId() {
		return this.msgId;
	}

	public void setMsgId(Long msgId) {
		this.msgId = msgId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	public Integer getMsgStatus() {
		return this.msgStatus;
	}

	public void setMsgStatus(Integer msgStatus) {
		this.msgStatus = msgStatus;
	}

	public Date getSenderTime() {
		return this.senderTime;
	}

	public void setSenderTime(Date senderTime) {
		this.senderTime = senderTime;
	}

	public Boolean getIsRead() {
		return this.isRead;
	}

	public void setIsRead(Boolean isRead) {
		this.isRead = isRead;
	}

	public Date getReadTime() {
		return this.readTime;
	}

	public void setReadTime(Date readTime) {
		this.readTime = readTime;
	}

	public String getMsgContent() {
		return this.msgContent;
	}

	public void setMsgContent(String msgContent) {
		this.msgContent = msgContent;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public Date getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	public Date getCreateOn() {
		return this.createOn;
	}

	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

}
