package com.times.acs.pojo.admin;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

// Generated 2013-7-12 18:27:13 by Hibernate Tools 3.4.0.CR1

/**
 * UserMapping generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true, value = { "hibernateLazyInitializer"})
public class UserMapping implements java.io.Serializable {

	private Long id;
	private String userCode;

	public UserMapping() {
	}

	public UserMapping(String userCode) {
		this.userCode = userCode;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

}
