package com.times.acs.pojo.admin;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

// Generated 2013-8-26 15:27:58 by Hibernate Tools 3.4.0.CR1

/**
 * UserGroupRelation generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(ignoreUnknown = true, value = { "hibernateLazyInitializer"})
public class UserGroupRelation implements java.io.Serializable {
	private static final long serialVersionUID = 7876290954290035354L;
	@Id
	@GeneratedValue
	private Long id;
	@ManyToOne
	private UserInfoPOJO user;
	@ManyToOne
	private UserGroupPOJO group;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public UserInfoPOJO getUser() {
		return user;
	}

	public void setUser(UserInfoPOJO user) {
		this.user = user;
	}

	public UserGroupPOJO getGroup() {
		return group;
	}

	public void setGroup(UserGroupPOJO group) {
		this.group = group;
	}

	public UserGroupRelation() {
	}

}
