package com.hm.bus.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-13T18:09:12.647+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://biz.webservice.macrosky.com/", name = "LoanService")
@XmlSeeAlso({ObjectFactory.class})
public interface LoanService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateStatusByAppId", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.UpdateStatusByAppId")
    @WebMethod
    @ResponseWrapper(localName = "updateStatusByAppIdResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.UpdateStatusByAppIdResponse")
    public com.hm.bus.webservice.TransModel updateStatusByAppId(
            @WebParam(name = "transHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "transBody", targetNamespace = "")
                    BasicOrder transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryBackTLonApplicationNumber", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryBackTLonApplicationNumber")
    @WebMethod
    @ResponseWrapper(localName = "queryBackTLonApplicationNumberResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryBackTLonApplicationNumberResponse")
    public com.hm.bus.webservice.TransModel queryBackTLonApplicationNumber(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    String transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryInstToPasService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryInstToPasService")
    @WebMethod
    @ResponseWrapper(localName = "queryInstToPasServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryInstToPasServiceResponse")
    public com.hm.bus.webservice.TransModel queryInstToPasService(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.PasInst transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "repRepaySyncCountAll", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RepRepaySyncCountAll")
    @WebMethod
    @ResponseWrapper(localName = "repRepaySyncCountAllResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RepRepaySyncCountAllResponse")
    public Integer repRepaySyncCountAll(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryBillAndFactorCount", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryBillAndFactorCount")
    @WebMethod
    @ResponseWrapper(localName = "queryBillAndFactorCountResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryBillAndFactorCountResponse")
    public int queryBillAndFactorCount(
            @WebParam(name = "arg0", targetNamespace = "")
                    BillFactCondition arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAppIdByNum", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.FindAppIdByNum")
    @WebMethod
    @ResponseWrapper(localName = "findAppIdByNumResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.FindAppIdByNumResponse")
    public java.util.List<com.hm.bus.webservice.TLonApplication> findAppIdByNum(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "bondValueSyncServiceAll", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.BondValueSyncServiceAll")
    @WebMethod
    @ResponseWrapper(localName = "bondValueSyncServiceAllResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.BondValueSyncServiceAllResponse")
    public Integer bondValueSyncServiceAll(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<com.hm.bus.webservice.AppId> arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMatchRepaymentBatch", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryMatchRepaymentBatch")
    @WebMethod
    @ResponseWrapper(localName = "queryMatchRepaymentBatchResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryMatchRepaymentBatchResponse")
    public java.util.List<com.hm.bus.webservice.TmatchRepayment> queryMatchRepaymentBatch(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Integer arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "salesCheckUploadService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.SalesCheckUploadService")
    @WebMethod
    @ResponseWrapper(localName = "salesCheckUploadServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.SalesCheckUploadServiceResponse")
    public com.hm.bus.webservice.TransModel salesCheckUploadService(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    LoanAttach transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "bondValueSyncService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.BondValueSyncService")
    @WebMethod
    @ResponseWrapper(localName = "bondValueSyncServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.BondValueSyncServiceResponse")
    public java.util.List<BondValueSync> bondValueSyncService(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<com.hm.bus.webservice.AppId> arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Integer arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWechatCustomer", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetWechatCustomer")
    @WebMethod
    @ResponseWrapper(localName = "getWechatCustomerResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetWechatCustomerResponse")
    public com.hm.bus.webservice.TransModel getWechatCustomer(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.WechatCustomerCondition transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generateContractForDaNiu", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GenerateContractForDaNiu")
    @WebMethod
    @ResponseWrapper(localName = "generateContractForDaNiuResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GenerateContractForDaNiuResponse")
    public String generateContractForDaNiu(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "YunDanAttachService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.YunDanAttachService")
    @WebMethod(operationName = "YunDanAttachService")
    @ResponseWrapper(localName = "YunDanAttachServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.YunDanAttachServiceResponse")
    public com.hm.bus.webservice.TransModel yunDanAttachService(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "tlonAttachList", targetNamespace = "")
                    java.util.List<com.hm.bus.webservice.TLonAttach> tlonAttachList,
            @WebParam(name = "appId", targetNamespace = "")
                    String appId,
            @WebParam(name = "saleChannel", targetNamespace = "")
                    String saleChannel,
            @WebParam(name = "productId", targetNamespace = "")
                    String productId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMatchOrder", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryMatchOrder")
    @WebMethod
    @ResponseWrapper(localName = "queryMatchOrderResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryMatchOrderResponse")
    public com.hm.bus.webservice.TransModel queryMatchOrder(
            @WebParam(name = "transHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "transBody", targetNamespace = "")
                    BasicOrder transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBusSeal", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetBusSeal")
    @WebMethod
    @ResponseWrapper(localName = "getBusSealResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetBusSealResponse")
    public String getBusSeal(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNewTLonApplicationNumber", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryNewTLonApplicationNumber")
    @WebMethod
    @ResponseWrapper(localName = "queryNewTLonApplicationNumberResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryNewTLonApplicationNumberResponse")
    public com.hm.bus.webservice.TransModel queryNewTLonApplicationNumber(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    String transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWXPCCustomer", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetWXPCCustomer")
    @WebMethod
    @ResponseWrapper(localName = "getWXPCCustomerResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetWXPCCustomerResponse")
    public com.hm.bus.webservice.TransModel getWXPCCustomer(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.WxpcCustomerCondition transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryProductToPasService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryProductToPasService")
    @WebMethod
    @ResponseWrapper(localName = "queryProductToPasServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryProductToPasServiceResponse")
    public com.hm.bus.webservice.TransModel queryProductToPasService(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.PasProduct transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "matchingAppStatusSyncService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.MatchingAppStatusSyncService")
    @WebMethod
    @ResponseWrapper(localName = "matchingAppStatusSyncServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.MatchingAppStatusSyncServiceResponse")
    public String matchingAppStatusSyncService(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<com.hm.bus.webservice.AppId> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ysxComService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.YsxComService")
    @WebMethod
    @ResponseWrapper(localName = "ysxComServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.YsxComServiceResponse")
    public com.hm.bus.webservice.TransModel ysxComService(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.YsXinfo transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generateRepaymentPlan", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GenerateRepaymentPlan")
    @WebMethod
    @ResponseWrapper(localName = "generateRepaymentPlanResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GenerateRepaymentPlanResponse")
    public String generateRepaymentPlan(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doPreCreditLimiteQuery", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPreCreditLimiteQuery")
    @WebMethod
    @ResponseWrapper(localName = "doPreCreditLimiteQueryResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPreCreditLimiteQueryResponse")
    public com.hm.bus.webservice.TransModel doPreCreditLimiteQuery(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.UserInfo58 transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doPeriodAppRecive", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPeriodAppRecive")
    @WebMethod
    @ResponseWrapper(localName = "doPeriodAppReciveResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPeriodAppReciveResponse")
    public com.hm.bus.webservice.TransModel doPeriodAppRecive(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    Contract58 transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMatchRepayment", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryMatchRepayment")
    @WebMethod
    @ResponseWrapper(localName = "queryMatchRepaymentResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryMatchRepaymentResponse")
    public com.hm.bus.webservice.TransModel queryMatchRepayment(
            @WebParam(name = "transHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "transBody", targetNamespace = "")
                    com.hm.bus.webservice.TmatchAppId transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getYanZheng", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetYanZheng")
    @WebMethod
    @ResponseWrapper(localName = "getYanZhengResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetYanZhengResponse")
    public String getYanZheng(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ysxAttachService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.YsxAttachService")
    @WebMethod
    @ResponseWrapper(localName = "ysxAttachServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.YsxAttachServiceResponse")
    public com.hm.bus.webservice.TransModel ysxAttachService(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.hm.bus.webservice.TransHead arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    com.hm.bus.webservice.WebYsxAttach arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAppIdByNums", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.FindAppIdByNums")
    @WebMethod
    @ResponseWrapper(localName = "findAppIdByNumsResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.FindAppIdByNumsResponse")
    public com.hm.bus.webservice.TransModel findAppIdByNums(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.hm.bus.webservice.TransHead arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generateContract", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GenerateContract")
    @WebMethod
    @ResponseWrapper(localName = "generateContractResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GenerateContractResponse")
    public String generateContract(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "seeContract", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.SeeContract")
    @WebMethod
    @ResponseWrapper(localName = "seeContractResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.SeeContractResponse")
    public String seeContract(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "credSynch", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.CredSynch")
    @WebMethod
    @ResponseWrapper(localName = "credSynchResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.CredSynchResponse")
    public com.hm.bus.webservice.TransModel credSynch(
            @WebParam(name = "transHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "transBody", targetNamespace = "")
                    BasicOrder transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doPreAuditAppGet", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPreAuditAppGet")
    @WebMethod
    @ResponseWrapper(localName = "doPreAuditAppGetResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPreAuditAppGetResponse")
    public com.hm.bus.webservice.TransModel doPreAuditAppGet(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.TLoanAppInstallments transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "RecordLoanAttachService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RecordLoanAttachService")
    @WebMethod(operationName = "RecordLoanAttachService")
    @ResponseWrapper(localName = "RecordLoanAttachServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RecordLoanAttachServiceResponse")
    public com.hm.bus.webservice.TransModel recordLoanAttachService(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    LoanAttach transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateProcess", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.UpdateProcess")
    @WebMethod
    @ResponseWrapper(localName = "updateProcessResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.UpdateProcessResponse")
    public com.hm.bus.webservice.TransModel updateProcess(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.TLonApplication transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryOrder", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryOrder")
    @WebMethod
    @ResponseWrapper(localName = "queryOrderResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryOrderResponse")
    public com.hm.bus.webservice.TransModel queryOrder(
            @WebParam(name = "transHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "transBody", targetNamespace = "")
                    BasicOrder transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "recordLoan", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RecordLoan")
    @WebMethod
    @ResponseWrapper(localName = "recordLoanResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RecordLoanResponse")
    public com.hm.bus.webservice.TransModel recordLoan(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.LonApp transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "overduePaymentFeedback", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.OverduePaymentFeedback")
    @WebMethod
    @ResponseWrapper(localName = "overduePaymentFeedbackResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.OverduePaymentFeedbackResponse")
    public com.hm.bus.webservice.TransModel overduePaymentFeedback(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.OverduePaymentBean transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "appStatusFeedback", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.AppStatusFeedback")
    @WebMethod
    @ResponseWrapper(localName = "appStatusFeedbackResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.AppStatusFeedbackResponse")
    public com.hm.bus.webservice.TransModel appStatusFeedback(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    AppStatusBean transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doPreAuditAppRecive", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPreAuditAppRecive")
    @WebMethod
    @ResponseWrapper(localName = "doPreAuditAppReciveResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPreAuditAppReciveResponse")
    public com.hm.bus.webservice.TransModel doPreAuditAppRecive(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.TLoanApp58 transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "realRepaySyncCountAll", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RealRepaySyncCountAll")
    @WebMethod
    @ResponseWrapper(localName = "realRepaySyncCountAllResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RealRepaySyncCountAllResponse")
    public Integer realRepaySyncCountAll(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveLatentCustomerService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.SaveLatentCustomerService")
    @WebMethod
    @ResponseWrapper(localName = "saveLatentCustomerServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.SaveLatentCustomerServiceResponse")
    public com.hm.bus.webservice.TransModel saveLatentCustomerService(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.TLatentCustomer transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doRePaymentQuery", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoRePaymentQuery")
    @WebMethod
    @ResponseWrapper(localName = "doRePaymentQueryResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoRePaymentQueryResponse")
    public com.hm.bus.webservice.TransModel doRePaymentQuery(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.Repayment58 transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryLoanToPasService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryLoanToPasService")
    @WebMethod
    @ResponseWrapper(localName = "queryLoanToPasServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryLoanToPasServiceResponse")
    public com.hm.bus.webservice.TransModel queryLoanToPasService(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.PasLoan transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doPreAuditAppCheck", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPreAuditAppCheck")
    @WebMethod
    @ResponseWrapper(localName = "doPreAuditAppCheckResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoPreAuditAppCheckResponse")
    public com.hm.bus.webservice.TransModel doPreAuditAppCheck(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    InstallmentGoCheckEntity transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateContract", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.UpdateContract")
    @WebMethod
    @ResponseWrapper(localName = "updateContractResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.UpdateContractResponse")
    public com.hm.bus.webservice.TransModel updateContract(
            @WebParam(name = "transHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "transBody", targetNamespace = "")
                    com.hm.bus.webservice.TLonApplicationContract transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkYanZheng", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.CheckYanZheng")
    @WebMethod
    @ResponseWrapper(localName = "checkYanZhengResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.CheckYanZhengResponse")
    public String checkYanZheng(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "haveLendAppSyncService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.HaveLendAppSyncService")
    @WebMethod
    @ResponseWrapper(localName = "haveLendAppSyncServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.HaveLendAppSyncServiceResponse")
    public java.util.List<com.hm.bus.webservice.MatchingAppSync> haveLendAppSyncService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "accountAndSignLoan", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.AccountAndSignLoan")
    @WebMethod
    @ResponseWrapper(localName = "accountAndSignLoanResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.AccountAndSignLoanResponse")
    public com.hm.bus.webservice.TransModel accountAndSignLoan(
            @WebParam(name = "transHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "transBody", targetNamespace = "")
                    ContractBean transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "calculateBonds", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.CalculateBonds")
    @WebMethod
    @ResponseWrapper(localName = "calculateBondsResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.CalculateBondsResponse")
    public com.hm.bus.webservice.TransModel calculateBonds(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.TApplicationBody transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "FullScaleAppSyncService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.FullScaleAppSyncService")
    @WebMethod(operationName = "FullScaleAppSyncService")
    @ResponseWrapper(localName = "FullScaleAppSyncServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.FullScaleAppSyncServiceResponse")
    public java.util.List<String> fullScaleAppSyncService(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<com.hm.bus.webservice.AppId> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "payPlayStatusFeedback", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.PayPlayStatusFeedback")
    @WebMethod
    @ResponseWrapper(localName = "payPlayStatusFeedbackResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.PayPlayStatusFeedbackResponse")
    public com.hm.bus.webservice.TransModel payPlayStatusFeedback(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.PayPlanRequestBean transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLoanStatus", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetLoanStatus")
    @WebMethod
    @ResponseWrapper(localName = "getLoanStatusResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetLoanStatusResponse")
    public com.hm.bus.webservice.TransModel getLoanStatus(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.StatusCondition transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateTLonUserkh", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.UpdateTLonUserkh")
    @WebMethod
    @ResponseWrapper(localName = "updateTLonUserkhResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.UpdateTLonUserkhResponse")
    public com.hm.bus.webservice.TransModel updateTLonUserkh(
            @WebParam(name = "transHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "transBody", targetNamespace = "")
                    com.hm.bus.webservice.TLonUserkh transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateCoustmor", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.ValidateCoustmor")
    @WebMethod
    @ResponseWrapper(localName = "validateCoustmorResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.ValidateCoustmorResponse")
    public com.hm.bus.webservice.TransModel validateCoustmor(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.ValidateMap transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "syncRepaymentInfos", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.SyncRepaymentInfos")
    @WebMethod
    @ResponseWrapper(localName = "syncRepaymentInfosResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.SyncRepaymentInfosResponse")
    public java.util.List<com.hm.bus.webservice.RePaymentWebServiceModel> syncRepaymentInfos(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryBillAndFactoringInfo", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryBillAndFactoringInfo")
    @WebMethod
    @ResponseWrapper(localName = "queryBillAndFactoringInfoResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryBillAndFactoringInfoResponse")
    public java.util.List<BillAndFactoring> queryBillAndFactoringInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    BillFactCondition arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doVehicleRecive", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoVehicleRecive")
    @WebMethod
    @ResponseWrapper(localName = "doVehicleReciveResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoVehicleReciveResponse")
    public com.hm.bus.webservice.TransModel doVehicleRecive(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    CarInfo58 transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doGetFundApply", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoGetFundApply")
    @WebMethod
    @ResponseWrapper(localName = "doGetFundApplyResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoGetFundApplyResponse")
    public com.hm.bus.webservice.TransModel doGetFundApply(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.Payment58 transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMatchRelation", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetMatchRelation")
    @WebMethod
    @ResponseWrapper(localName = "getMatchRelationResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetMatchRelationResponse")
    public com.hm.bus.webservice.TransModel getMatchRelation(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.LonAppPayXML transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "matchingAppSyncService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.MatchingAppSyncService")
    @WebMethod
    @ResponseWrapper(localName = "matchingAppSyncServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.MatchingAppSyncServiceResponse")
    public java.util.List<com.hm.bus.webservice.MatchingAppSync> matchingAppSyncService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doGetMortgagorList", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoGetMortgagorList")
    @WebMethod
    @ResponseWrapper(localName = "doGetMortgagorListResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.DoGetMortgagorListResponse")
    public com.hm.bus.webservice.TransModel doGetMortgagorList(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    com.hm.bus.webservice.TLoanAppInstallments transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWechatContractAlgorithm", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetWechatContractAlgorithm")
    @WebMethod
    @ResponseWrapper(localName = "getWechatContractAlgorithmResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.GetWechatContractAlgorithmResponse")
    public com.hm.bus.webservice.TransModel getWechatContractAlgorithm(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    ContractCondition transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryRepayment", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryRepayment")
    @WebMethod
    @ResponseWrapper(localName = "queryRepaymentResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.QueryRepaymentResponse")
    public com.hm.bus.webservice.TransModel queryRepayment(
            @WebParam(name = "TransHead", targetNamespace = "")
                    com.hm.bus.webservice.TransHead transHead,
            @WebParam(name = "TransBody", targetNamespace = "")
                    String transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "realRepaySyncService", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RealRepaySyncService")
    @WebMethod
    @ResponseWrapper(localName = "realRepaySyncServiceResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.hm.bus.webservice.RealRepaySyncServiceResponse")
    public java.util.List<com.hm.bus.webservice.RealRepaySync> realRepaySyncService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Integer arg2
    );
}
