
package com.hm.bus.webservice.cnloan;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-12-02T12:12:52.152+08:00
 * Generated source version: 3.1.1
 * 
 */
public final class CnLoanService_CnLoanServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("microloan", "cnLoanService");

    private CnLoanService_CnLoanServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CnLoanService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CnLoanService_Service ss = new CnLoanService_Service(wsdlURL, SERVICE_NAME);
        CnLoanService port = ss.getCnLoanServiceImplPort();  
        
        {
        System.out.println("Invoking cnEditAppInfo...");
        com.hm.bus.webservice.cnloan.TransHead _cnEditAppInfo_transHead = null;
        com.hm.bus.webservice.cnloan.TIndApplication _cnEditAppInfo_transBody = null;
        com.hm.bus.webservice.cnloan.TransModel _cnEditAppInfo__return = port.cnEditAppInfo(_cnEditAppInfo_transHead, _cnEditAppInfo_transBody);
        System.out.println("cnEditAppInfo.result=" + _cnEditAppInfo__return);


        }
        {
        System.out.println("Invoking generateRepaymentNotices...");
        com.hm.bus.webservice.cnloan.TransHead _generateRepaymentNotices_transHead = null;
        java.util.List<com.hm.bus.webservice.cnloan.RepaymentNoticeModel> _generateRepaymentNotices_transBody = null;
        com.hm.bus.webservice.cnloan.TransModel _generateRepaymentNotices__return = port.generateRepaymentNotices(_generateRepaymentNotices_transHead, _generateRepaymentNotices_transBody);
        System.out.println("generateRepaymentNotices.result=" + _generateRepaymentNotices__return);


        }

        System.exit(0);
    }

}
