package com.hm.bus.webservice.cnloan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-12-02T12:12:52.230+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "cnLoanService", 
                  wsdlLocation = "http://cls.9fbank.com:9097/webservice/cnLoanService?wsdl",
                  targetNamespace = "microloan") 
public class CnLoanService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("microloan", "cnLoanService");
    public final static QName CnLoanServiceImplPort = new QName("microloan", "CnLoanServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://cls.9fbank.com:9097/webservice/cnLoanService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CnLoanService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://cls.9fbank.com:9097/webservice/cnLoanService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CnLoanService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CnLoanService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CnLoanService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CnLoanService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CnLoanService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CnLoanService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CnLoanService
     */
    @WebEndpoint(name = "CnLoanServiceImplPort")
    public CnLoanService getCnLoanServiceImplPort() {
        return super.getPort(CnLoanServiceImplPort, CnLoanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CnLoanService
     */
    @WebEndpoint(name = "CnLoanServiceImplPort")
    public CnLoanService getCnLoanServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CnLoanServiceImplPort, CnLoanService.class, features);
    }

}
