package com.hm.bus.webservice.cnloan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-12-02T12:12:52.230+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://webservice.cicada.jfbank.com/", name = "CnLoanService")
@XmlSeeAlso({ObjectFactory.class})
public interface CnLoanService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cnEditAppInfo", targetNamespace = "http://webservice.cicada.jfbank.com/", className = "com.hm.bus.webservice.cnloan.CnEditAppInfo")
    @WebMethod
    @ResponseWrapper(localName = "cnEditAppInfoResponse", targetNamespace = "http://webservice.cicada.jfbank.com/", className = "com.hm.bus.webservice.cnloan.CnEditAppInfoResponse")
    public com.hm.bus.webservice.cnloan.TransModel cnEditAppInfo(
        @WebParam(name = "TransHead", targetNamespace = "")
        com.hm.bus.webservice.cnloan.TransHead transHead,
        @WebParam(name = "TransBody", targetNamespace = "")
        com.hm.bus.webservice.cnloan.TIndApplication transBody
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generateRepaymentNotices", targetNamespace = "http://webservice.cicada.jfbank.com/", className = "com.hm.bus.webservice.cnloan.GenerateRepaymentNotices")
    @WebMethod
    @ResponseWrapper(localName = "generateRepaymentNoticesResponse", targetNamespace = "http://webservice.cicada.jfbank.com/", className = "com.hm.bus.webservice.cnloan.GenerateRepaymentNoticesResponse")
    public com.hm.bus.webservice.cnloan.TransModel generateRepaymentNotices(
        @WebParam(name = "TransHead", targetNamespace = "")
        com.hm.bus.webservice.cnloan.TransHead transHead,
        @WebParam(name = "TransBody", targetNamespace = "")
        java.util.List<com.hm.bus.webservice.cnloan.RepaymentNoticeModel> transBody
    );
}
