package com.hm.appinfo.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @ClassName: LnAppProcess
 * @Description: 贷款工单审核流程实体
 * @author qiuyuan
 * @date 2016年4月11日 下午2:24:04
 * @Copyright (c) 2016, 9fchaoneng.com All Rights Reserved.
 */
public class LnAppProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.AUDIT_FD_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date auditFdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long auditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.AUDIT_BEGIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date auditBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.AUTID_END_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date autidEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.AUDIT_SUGGEST
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String auditSuggest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.SPE_AUDIT_BEGIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date speAuditBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.SPE_AUDIT_END_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date speAuditEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.SPE_AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long speAuditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.SPE_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String speAuditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.SPE_AUDIT_SUGGEST
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String speAuditSuggest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.FIRST_GRADE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date firstGradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.FIRST_GRADE_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String firstGradeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.FIRST_GRADE_LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String firstGradeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.SEC_GRADE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date secGradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.SEC_GRADE_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String secGradeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.SEC_GRADE_LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String secGradeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.LAST_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String lastAuditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONT_AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long contAuditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONT_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contAuditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONT_AUDIT_BACK_REASON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contAuditBackReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONT_AUDIT_BACK_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date contAuditBackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONT_AUDIT_FD_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date contAuditFdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.LAST_UPDATE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.FIRST_GRADES
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private BigDecimal firstGrades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.RISK_GRADES
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private BigDecimal riskGrades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.AUDIT_FIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long auditFinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONTRACT_EXAMINER_HOST_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long contractExaminerHostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONTRACT_EXAMINER_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contractExaminerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONTRACT_EXAMINE_SUGGESTION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contractExamineSuggestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONTRACT_EXAMINE_STATUS_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contractExamineStatusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CONTRACT_EXAMINE_STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String contractExamineStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date createdon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date modifiedon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.END_REASON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String endReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.END_STATUS_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String endStatusType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.FLOW_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String flowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_process.BACK_CAUSE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String backCause;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.ID
     *
     * @return the value of ln_app_process.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.ID
     *
     * @param id the value for ln_app_process.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.APP_ID
     *
     * @return the value of ln_app_process.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.APP_ID
     *
     * @param appId the value for ln_app_process.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.AUDIT_FD_TIME
     *
     * @return the value of ln_app_process.AUDIT_FD_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getAuditFdTime() {
        return auditFdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.AUDIT_FD_TIME
     *
     * @param auditFdTime the value for ln_app_process.AUDIT_FD_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAuditFdTime(Date auditFdTime) {
        this.auditFdTime = auditFdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.AUDIT_ID
     *
     * @return the value of ln_app_process.AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.AUDIT_ID
     *
     * @param auditId the value for ln_app_process.AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAuditId(Long auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.AUDIT_BEGIN_TIME
     *
     * @return the value of ln_app_process.AUDIT_BEGIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getAuditBeginTime() {
        return auditBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.AUDIT_BEGIN_TIME
     *
     * @param auditBeginTime the value for ln_app_process.AUDIT_BEGIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAuditBeginTime(Date auditBeginTime) {
        this.auditBeginTime = auditBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.AUTID_END_TIME
     *
     * @return the value of ln_app_process.AUTID_END_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getAutidEndTime() {
        return autidEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.AUTID_END_TIME
     *
     * @param autidEndTime the value for ln_app_process.AUTID_END_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAutidEndTime(Date autidEndTime) {
        this.autidEndTime = autidEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.AUDIT_SUGGEST
     *
     * @return the value of ln_app_process.AUDIT_SUGGEST
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getAuditSuggest() {
        return auditSuggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.AUDIT_SUGGEST
     *
     * @param auditSuggest the value for ln_app_process.AUDIT_SUGGEST
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAuditSuggest(String auditSuggest) {
        this.auditSuggest = auditSuggest == null ? null : auditSuggest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.SPE_AUDIT_BEGIN_TIME
     *
     * @return the value of ln_app_process.SPE_AUDIT_BEGIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getSpeAuditBeginTime() {
        return speAuditBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.SPE_AUDIT_BEGIN_TIME
     *
     * @param speAuditBeginTime the value for ln_app_process.SPE_AUDIT_BEGIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSpeAuditBeginTime(Date speAuditBeginTime) {
        this.speAuditBeginTime = speAuditBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.SPE_AUDIT_END_TIME
     *
     * @return the value of ln_app_process.SPE_AUDIT_END_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getSpeAuditEndTime() {
        return speAuditEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.SPE_AUDIT_END_TIME
     *
     * @param speAuditEndTime the value for ln_app_process.SPE_AUDIT_END_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSpeAuditEndTime(Date speAuditEndTime) {
        this.speAuditEndTime = speAuditEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.SPE_AUDIT_ID
     *
     * @return the value of ln_app_process.SPE_AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getSpeAuditId() {
        return speAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.SPE_AUDIT_ID
     *
     * @param speAuditId the value for ln_app_process.SPE_AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSpeAuditId(Long speAuditId) {
        this.speAuditId = speAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.SPE_AUDIT_RESULT
     *
     * @return the value of ln_app_process.SPE_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getSpeAuditResult() {
        return speAuditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.SPE_AUDIT_RESULT
     *
     * @param speAuditResult the value for ln_app_process.SPE_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSpeAuditResult(String speAuditResult) {
        this.speAuditResult = speAuditResult == null ? null : speAuditResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.SPE_AUDIT_SUGGEST
     *
     * @return the value of ln_app_process.SPE_AUDIT_SUGGEST
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getSpeAuditSuggest() {
        return speAuditSuggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.SPE_AUDIT_SUGGEST
     *
     * @param speAuditSuggest the value for ln_app_process.SPE_AUDIT_SUGGEST
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSpeAuditSuggest(String speAuditSuggest) {
        this.speAuditSuggest = speAuditSuggest == null ? null : speAuditSuggest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.FIRST_GRADE_TIME
     *
     * @return the value of ln_app_process.FIRST_GRADE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getFirstGradeTime() {
        return firstGradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.FIRST_GRADE_TIME
     *
     * @param firstGradeTime the value for ln_app_process.FIRST_GRADE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFirstGradeTime(Date firstGradeTime) {
        this.firstGradeTime = firstGradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.FIRST_GRADE_RESULT
     *
     * @return the value of ln_app_process.FIRST_GRADE_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getFirstGradeResult() {
        return firstGradeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.FIRST_GRADE_RESULT
     *
     * @param firstGradeResult the value for ln_app_process.FIRST_GRADE_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFirstGradeResult(String firstGradeResult) {
        this.firstGradeResult = firstGradeResult == null ? null : firstGradeResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.FIRST_GRADE_LEVEL
     *
     * @return the value of ln_app_process.FIRST_GRADE_LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getFirstGradeLevel() {
        return firstGradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.FIRST_GRADE_LEVEL
     *
     * @param firstGradeLevel the value for ln_app_process.FIRST_GRADE_LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFirstGradeLevel(String firstGradeLevel) {
        this.firstGradeLevel = firstGradeLevel == null ? null : firstGradeLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.SEC_GRADE_TIME
     *
     * @return the value of ln_app_process.SEC_GRADE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getSecGradeTime() {
        return secGradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.SEC_GRADE_TIME
     *
     * @param secGradeTime the value for ln_app_process.SEC_GRADE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSecGradeTime(Date secGradeTime) {
        this.secGradeTime = secGradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.SEC_GRADE_RESULT
     *
     * @return the value of ln_app_process.SEC_GRADE_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getSecGradeResult() {
        return secGradeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.SEC_GRADE_RESULT
     *
     * @param secGradeResult the value for ln_app_process.SEC_GRADE_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSecGradeResult(String secGradeResult) {
        this.secGradeResult = secGradeResult == null ? null : secGradeResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.SEC_GRADE_LEVEL
     *
     * @return the value of ln_app_process.SEC_GRADE_LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getSecGradeLevel() {
        return secGradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.SEC_GRADE_LEVEL
     *
     * @param secGradeLevel the value for ln_app_process.SEC_GRADE_LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSecGradeLevel(String secGradeLevel) {
        this.secGradeLevel = secGradeLevel == null ? null : secGradeLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.LAST_AUDIT_RESULT
     *
     * @return the value of ln_app_process.LAST_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getLastAuditResult() {
        return lastAuditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.LAST_AUDIT_RESULT
     *
     * @param lastAuditResult the value for ln_app_process.LAST_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setLastAuditResult(String lastAuditResult) {
        this.lastAuditResult = lastAuditResult == null ? null : lastAuditResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONT_AUDIT_ID
     *
     * @return the value of ln_app_process.CONT_AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getContAuditId() {
        return contAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONT_AUDIT_ID
     *
     * @param contAuditId the value for ln_app_process.CONT_AUDIT_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContAuditId(Long contAuditId) {
        this.contAuditId = contAuditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONT_AUDIT_RESULT
     *
     * @return the value of ln_app_process.CONT_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContAuditResult() {
        return contAuditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONT_AUDIT_RESULT
     *
     * @param contAuditResult the value for ln_app_process.CONT_AUDIT_RESULT
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContAuditResult(String contAuditResult) {
        this.contAuditResult = contAuditResult == null ? null : contAuditResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONT_AUDIT_BACK_REASON
     *
     * @return the value of ln_app_process.CONT_AUDIT_BACK_REASON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContAuditBackReason() {
        return contAuditBackReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONT_AUDIT_BACK_REASON
     *
     * @param contAuditBackReason the value for ln_app_process.CONT_AUDIT_BACK_REASON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContAuditBackReason(String contAuditBackReason) {
        this.contAuditBackReason = contAuditBackReason == null ? null : contAuditBackReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONT_AUDIT_BACK_TIME
     *
     * @return the value of ln_app_process.CONT_AUDIT_BACK_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getContAuditBackTime() {
        return contAuditBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONT_AUDIT_BACK_TIME
     *
     * @param contAuditBackTime the value for ln_app_process.CONT_AUDIT_BACK_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContAuditBackTime(Date contAuditBackTime) {
        this.contAuditBackTime = contAuditBackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONT_AUDIT_FD_TIME
     *
     * @return the value of ln_app_process.CONT_AUDIT_FD_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getContAuditFdTime() {
        return contAuditFdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONT_AUDIT_FD_TIME
     *
     * @param contAuditFdTime the value for ln_app_process.CONT_AUDIT_FD_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContAuditFdTime(Date contAuditFdTime) {
        this.contAuditFdTime = contAuditFdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.LAST_UPDATE_TIME
     *
     * @return the value of ln_app_process.LAST_UPDATE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for ln_app_process.LAST_UPDATE_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.FIRST_GRADES
     *
     * @return the value of ln_app_process.FIRST_GRADES
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public BigDecimal getFirstGrades() {
        return firstGrades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.FIRST_GRADES
     *
     * @param firstGrades the value for ln_app_process.FIRST_GRADES
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFirstGrades(BigDecimal firstGrades) {
        this.firstGrades = firstGrades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.RISK_GRADES
     *
     * @return the value of ln_app_process.RISK_GRADES
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public BigDecimal getRiskGrades() {
        return riskGrades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.RISK_GRADES
     *
     * @param riskGrades the value for ln_app_process.RISK_GRADES
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setRiskGrades(BigDecimal riskGrades) {
        this.riskGrades = riskGrades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.AUDIT_FIN_TIME
     *
     * @return the value of ln_app_process.AUDIT_FIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getAuditFinTime() {
        return auditFinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.AUDIT_FIN_TIME
     *
     * @param auditFinTime the value for ln_app_process.AUDIT_FIN_TIME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAuditFinTime(Long auditFinTime) {
        this.auditFinTime = auditFinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONTRACT_EXAMINER_HOST_ID
     *
     * @return the value of ln_app_process.CONTRACT_EXAMINER_HOST_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getContractExaminerHostId() {
        return contractExaminerHostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONTRACT_EXAMINER_HOST_ID
     *
     * @param contractExaminerHostId the value for ln_app_process.CONTRACT_EXAMINER_HOST_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractExaminerHostId(Long contractExaminerHostId) {
        this.contractExaminerHostId = contractExaminerHostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONTRACT_EXAMINER_NAME
     *
     * @return the value of ln_app_process.CONTRACT_EXAMINER_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContractExaminerName() {
        return contractExaminerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONTRACT_EXAMINER_NAME
     *
     * @param contractExaminerName the value for ln_app_process.CONTRACT_EXAMINER_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractExaminerName(String contractExaminerName) {
        this.contractExaminerName = contractExaminerName == null ? null : contractExaminerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONTRACT_EXAMINE_SUGGESTION
     *
     * @return the value of ln_app_process.CONTRACT_EXAMINE_SUGGESTION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContractExamineSuggestion() {
        return contractExamineSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONTRACT_EXAMINE_SUGGESTION
     *
     * @param contractExamineSuggestion the value for ln_app_process.CONTRACT_EXAMINE_SUGGESTION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractExamineSuggestion(String contractExamineSuggestion) {
        this.contractExamineSuggestion = contractExamineSuggestion == null ? null : contractExamineSuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONTRACT_EXAMINE_STATUS_NAME
     *
     * @return the value of ln_app_process.CONTRACT_EXAMINE_STATUS_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContractExamineStatusName() {
        return contractExamineStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONTRACT_EXAMINE_STATUS_NAME
     *
     * @param contractExamineStatusName the value for ln_app_process.CONTRACT_EXAMINE_STATUS_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractExamineStatusName(String contractExamineStatusName) {
        this.contractExamineStatusName = contractExamineStatusName == null ? null : contractExamineStatusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CONTRACT_EXAMINE_STATUS
     *
     * @return the value of ln_app_process.CONTRACT_EXAMINE_STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getContractExamineStatus() {
        return contractExamineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CONTRACT_EXAMINE_STATUS
     *
     * @param contractExamineStatus the value for ln_app_process.CONTRACT_EXAMINE_STATUS
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setContractExamineStatus(String contractExamineStatus) {
        this.contractExamineStatus = contractExamineStatus == null ? null : contractExamineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CREATEDBY
     *
     * @return the value of ln_app_process.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CREATEDBY
     *
     * @param createdby the value for ln_app_process.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.CREATEDON
     *
     * @return the value of ln_app_process.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getCreatedon() {
        return createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.CREATEDON
     *
     * @param createdon the value for ln_app_process.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.MODIFIEDBY
     *
     * @return the value of ln_app_process.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.MODIFIEDBY
     *
     * @param modifiedby the value for ln_app_process.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby == null ? null : modifiedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.MODIFIEDON
     *
     * @return the value of ln_app_process.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getModifiedon() {
        return modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.MODIFIEDON
     *
     * @param modifiedon the value for ln_app_process.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.VERSION
     *
     * @return the value of ln_app_process.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.VERSION
     *
     * @param version the value for ln_app_process.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.END_REASON
     *
     * @return the value of ln_app_process.END_REASON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getEndReason() {
        return endReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.END_REASON
     *
     * @param endReason the value for ln_app_process.END_REASON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setEndReason(String endReason) {
        this.endReason = endReason == null ? null : endReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.END_STATUS_TYPE
     *
     * @return the value of ln_app_process.END_STATUS_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getEndStatusType() {
        return endStatusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.END_STATUS_TYPE
     *
     * @param endStatusType the value for ln_app_process.END_STATUS_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setEndStatusType(String endStatusType) {
        this.endStatusType = endStatusType == null ? null : endStatusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.FLOW_TYPE
     *
     * @return the value of ln_app_process.FLOW_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getFlowType() {
        return flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.FLOW_TYPE
     *
     * @param flowType the value for ln_app_process.FLOW_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFlowType(String flowType) {
        this.flowType = flowType == null ? null : flowType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_process.BACK_CAUSE
     *
     * @return the value of ln_app_process.BACK_CAUSE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getBackCause() {
        return backCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_process.BACK_CAUSE
     *
     * @param backCause the value for ln_app_process.BACK_CAUSE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setBackCause(String backCause) {
        this.backCause = backCause == null ? null : backCause.trim();
    }
}