package com.hm.bus.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-13T18:09:12.675+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "loanService", 
                  wsdlLocation = "http://123.57.48.237:7082/webservice/loanService?wsdl",
                  targetNamespace = "microloan") 
public class LoanService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("microloan", "loanService");
    public final static QName LoanServiceImplPort = new QName("microloan", "LoanServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://123.57.48.237:7082/webservice/loanService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoanService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://123.57.48.237:7082/webservice/loanService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoanService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoanService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LoanService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LoanService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LoanService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LoanService
     */
    @WebEndpoint(name = "LoanServiceImplPort")
    public LoanService getLoanServiceImplPort() {
        return super.getPort(LoanServiceImplPort, LoanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanService
     */
    @WebEndpoint(name = "LoanServiceImplPort")
    public LoanService getLoanServiceImplPort(WebServiceFeature... features) {
        return super.getPort(LoanServiceImplPort, LoanService.class, features);
    }

}
