package com.hm.appinfo.model;

import java.util.Date;

public class LnAppStatusChangeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.ID
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.APP_ID
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.STATUS
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.NEW_STATUS
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private String newStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.CHANGE_TIME
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.CHANGE_USER
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private String changeUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.DESP
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private String desp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.CREATEDBY
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.CREATEDON
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private Date createdon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.MODIFIEDBY
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private String modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.MODIFIEDON
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private Date modifiedon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_app_statuschangelog.VERSION
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.ID
     *
     * @return the value of ln_app_statuschangelog.ID
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.ID
     *
     * @param id the value for ln_app_statuschangelog.ID
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.APP_ID
     *
     * @return the value of ln_app_statuschangelog.APP_ID
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.APP_ID
     *
     * @param appId the value for ln_app_statuschangelog.APP_ID
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.STATUS
     *
     * @return the value of ln_app_statuschangelog.STATUS
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.STATUS
     *
     * @param status the value for ln_app_statuschangelog.STATUS
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.NEW_STATUS
     *
     * @return the value of ln_app_statuschangelog.NEW_STATUS
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public String getNewStatus() {
        return newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.NEW_STATUS
     *
     * @param newStatus the value for ln_app_statuschangelog.NEW_STATUS
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setNewStatus(String newStatus) {
        this.newStatus = newStatus == null ? null : newStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.CHANGE_TIME
     *
     * @return the value of ln_app_statuschangelog.CHANGE_TIME
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.CHANGE_TIME
     *
     * @param changeTime the value for ln_app_statuschangelog.CHANGE_TIME
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.CHANGE_USER
     *
     * @return the value of ln_app_statuschangelog.CHANGE_USER
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public String getChangeUser() {
        return changeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.CHANGE_USER
     *
     * @param changeUser the value for ln_app_statuschangelog.CHANGE_USER
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setChangeUser(String changeUser) {
        this.changeUser = changeUser == null ? null : changeUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.DESP
     *
     * @return the value of ln_app_statuschangelog.DESP
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public String getDesp() {
        return desp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.DESP
     *
     * @param desp the value for ln_app_statuschangelog.DESP
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setDesp(String desp) {
        this.desp = desp == null ? null : desp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.CREATEDBY
     *
     * @return the value of ln_app_statuschangelog.CREATEDBY
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.CREATEDBY
     *
     * @param createdby the value for ln_app_statuschangelog.CREATEDBY
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.CREATEDON
     *
     * @return the value of ln_app_statuschangelog.CREATEDON
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public Date getCreatedon() {
        return createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.CREATEDON
     *
     * @param createdon the value for ln_app_statuschangelog.CREATEDON
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.MODIFIEDBY
     *
     * @return the value of ln_app_statuschangelog.MODIFIEDBY
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public String getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.MODIFIEDBY
     *
     * @param modifiedby the value for ln_app_statuschangelog.MODIFIEDBY
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby == null ? null : modifiedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.MODIFIEDON
     *
     * @return the value of ln_app_statuschangelog.MODIFIEDON
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public Date getModifiedon() {
        return modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.MODIFIEDON
     *
     * @param modifiedon the value for ln_app_statuschangelog.MODIFIEDON
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_app_statuschangelog.VERSION
     *
     * @return the value of ln_app_statuschangelog.VERSION
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_app_statuschangelog.VERSION
     *
     * @param version the value for ln_app_statuschangelog.VERSION
     *
     * @mbggenerated Tue Apr 26 12:15:59 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}