package com.hm.bus.module;

import java.util.Date;

public class JjCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.ID
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.Code
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.Name
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.GroupID
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private Long groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.Version
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.CreateBy
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.ModifyBy
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private String modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.ModifyOn
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private Date modifyon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.CreateOn
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private Date createon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.orderIndex
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private Integer orderindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jj_code.AppCode
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    private String appcode;
    
    private String groupCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.ID
     *
     * @return the value of jj_code.ID
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.ID
     *
     * @param id the value for jj_code.ID
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.Code
     *
     * @return the value of jj_code.Code
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.Code
     *
     * @param code the value for jj_code.Code
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.Name
     *
     * @return the value of jj_code.Name
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.Name
     *
     * @param name the value for jj_code.Name
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.GroupID
     *
     * @return the value of jj_code.GroupID
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.GroupID
     *
     * @param groupid the value for jj_code.GroupID
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.Version
     *
     * @return the value of jj_code.Version
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.Version
     *
     * @param version the value for jj_code.Version
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.CreateBy
     *
     * @return the value of jj_code.CreateBy
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.CreateBy
     *
     * @param createby the value for jj_code.CreateBy
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.ModifyBy
     *
     * @return the value of jj_code.ModifyBy
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public String getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.ModifyBy
     *
     * @param modifyby the value for jj_code.ModifyBy
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setModifyby(String modifyby) {
        this.modifyby = modifyby == null ? null : modifyby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.ModifyOn
     *
     * @return the value of jj_code.ModifyOn
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public Date getModifyon() {
        return modifyon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.ModifyOn
     *
     * @param modifyon the value for jj_code.ModifyOn
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setModifyon(Date modifyon) {
        this.modifyon = modifyon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.CreateOn
     *
     * @return the value of jj_code.CreateOn
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public Date getCreateon() {
        return createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.CreateOn
     *
     * @param createon the value for jj_code.CreateOn
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setCreateon(Date createon) {
        this.createon = createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.orderIndex
     *
     * @return the value of jj_code.orderIndex
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public Integer getOrderindex() {
        return orderindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.orderIndex
     *
     * @param orderindex the value for jj_code.orderIndex
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setOrderindex(Integer orderindex) {
        this.orderindex = orderindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jj_code.AppCode
     *
     * @return the value of jj_code.AppCode
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public String getAppcode() {
        return appcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jj_code.AppCode
     *
     * @param appcode the value for jj_code.AppCode
     *
     * @mbggenerated Wed Apr 13 18:15:10 GMT+08:00 2016
     */
    public void setAppcode(String appcode) {
        this.appcode = appcode == null ? null : appcode.trim();
    }

	public String getGroupCode()
	{
		return groupCode;
	}

	public void setGroupCode(String groupCode)
	{
		this.groupCode = groupCode;
	}
}