package com.hm.bus.module;


import java.util.Date;

/**
 * @ClassName: LnAttachInfo
 * @Description: 贷款附件表
 * @author qiuyuan
 * @date 2016年4月11日 下午2:25:03
 * @Copyright (c) 2016, 9fchaoneng.com All Rights Reserved.
 */
public class LnAttachInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.ATTACH_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String attachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.ATTACH_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String attachName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.ATTACH_URL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String attachUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.FILE_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.FILE_SIZE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.FILE_SERIAL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String fileSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.REMARK
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date createdon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String modifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Date modifiedon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.OSS_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String ossId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.CAREER_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String careerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.CHOOSE_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String chooseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.PRODUCT_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ln_attach_info.SOURCE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    private String source;
    
    private String parentCode;
    private String parentAccessoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.ID
     *
     * @return the value of ln_attach_info.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.ID
     *
     * @param id the value for ln_attach_info.ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.APP_ID
     *
     * @return the value of ln_attach_info.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.APP_ID
     *
     * @param appId the value for ln_attach_info.APP_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.ATTACH_TYPE
     *
     * @return the value of ln_attach_info.ATTACH_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getAttachType() {
        return attachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.ATTACH_TYPE
     *
     * @param attachType the value for ln_attach_info.ATTACH_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAttachType(String attachType) {
        this.attachType = attachType == null ? null : attachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.ATTACH_NAME
     *
     * @return the value of ln_attach_info.ATTACH_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getAttachName() {
        return attachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.ATTACH_NAME
     *
     * @param attachName the value for ln_attach_info.ATTACH_NAME
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAttachName(String attachName) {
        this.attachName = attachName == null ? null : attachName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.ATTACH_URL
     *
     * @return the value of ln_attach_info.ATTACH_URL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getAttachUrl() {
        return attachUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.ATTACH_URL
     *
     * @param attachUrl the value for ln_attach_info.ATTACH_URL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setAttachUrl(String attachUrl) {
        this.attachUrl = attachUrl == null ? null : attachUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.FILE_TYPE
     *
     * @return the value of ln_attach_info.FILE_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.FILE_TYPE
     *
     * @param fileType the value for ln_attach_info.FILE_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.FILE_SIZE
     *
     * @return the value of ln_attach_info.FILE_SIZE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.FILE_SIZE
     *
     * @param fileSize the value for ln_attach_info.FILE_SIZE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.FILE_SERIAL
     *
     * @return the value of ln_attach_info.FILE_SERIAL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getFileSerial() {
        return fileSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.FILE_SERIAL
     *
     * @param fileSerial the value for ln_attach_info.FILE_SERIAL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setFileSerial(String fileSerial) {
        this.fileSerial = fileSerial == null ? null : fileSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.REMARK
     *
     * @return the value of ln_attach_info.REMARK
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.REMARK
     *
     * @param remark the value for ln_attach_info.REMARK
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.CREATEDBY
     *
     * @return the value of ln_attach_info.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.CREATEDBY
     *
     * @param createdby the value for ln_attach_info.CREATEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.CREATEDON
     *
     * @return the value of ln_attach_info.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getCreatedon() {
        return createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.CREATEDON
     *
     * @param createdon the value for ln_attach_info.CREATEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.MODIFIEDBY
     *
     * @return the value of ln_attach_info.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.MODIFIEDBY
     *
     * @param modifiedby the value for ln_attach_info.MODIFIEDBY
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setModifiedby(String modifiedby) {
        this.modifiedby = modifiedby == null ? null : modifiedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.MODIFIEDON
     *
     * @return the value of ln_attach_info.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Date getModifiedon() {
        return modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.MODIFIEDON
     *
     * @param modifiedon the value for ln_attach_info.MODIFIEDON
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.VERSION
     *
     * @return the value of ln_attach_info.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.VERSION
     *
     * @param version the value for ln_attach_info.VERSION
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.OSS_ID
     *
     * @return the value of ln_attach_info.OSS_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getOssId() {
        return ossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.OSS_ID
     *
     * @param ossId the value for ln_attach_info.OSS_ID
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setOssId(String ossId) {
        this.ossId = ossId == null ? null : ossId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.CAREER_TYPE
     *
     * @return the value of ln_attach_info.CAREER_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getCareerType() {
        return careerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.CAREER_TYPE
     *
     * @param careerType the value for ln_attach_info.CAREER_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setCareerType(String careerType) {
        this.careerType = careerType == null ? null : careerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.LEVEL
     *
     * @return the value of ln_attach_info.LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.LEVEL
     *
     * @param level the value for ln_attach_info.LEVEL
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.CHOOSE_TYPE
     *
     * @return the value of ln_attach_info.CHOOSE_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getChooseType() {
        return chooseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.CHOOSE_TYPE
     *
     * @param chooseType the value for ln_attach_info.CHOOSE_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setChooseType(String chooseType) {
        this.chooseType = chooseType == null ? null : chooseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.PRODUCT_TYPE
     *
     * @return the value of ln_attach_info.PRODUCT_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.PRODUCT_TYPE
     *
     * @param productType the value for ln_attach_info.PRODUCT_TYPE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ln_attach_info.SOURCE
     *
     * @return the value of ln_attach_info.SOURCE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ln_attach_info.SOURCE
     *
     * @param source the value for ln_attach_info.SOURCE
     *
     * @mbggenerated Mon Apr 11 14:11:00 GMT+08:00 2016
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }
    
    
    /*public String getOssIdUrl() {
    	if (InputChecker.isEmpty(ossId))
		{
    		return "";
		}
        return OssOps.getSignUrl(ossId);
    }*/

	public String getParentCode()
	{
		return parentCode;
	}

	public void setParentCode(String parentCode)
	{
		this.parentCode = parentCode;
	}

	public String getParentAccessoryName()
	{
		return parentAccessoryName;
	}

	public void setParentAccessoryName(String parentAccessoryName)
	{
		this.parentAccessoryName = parentAccessoryName;
	}
    
	private String examineSeqNo;
	private Long examineBatchNo;
	

	public Long getExamineBatchNo() {
		return examineBatchNo;
	}

	public void setExamineBatchNo(Long examineBatchNo) {
		this.examineBatchNo = examineBatchNo;
	}

	public String getExamineSeqNo() {
		return examineSeqNo;
	}

	public void setExamineSeqNo(String examineSeqNo) {
		this.examineSeqNo = examineSeqNo;
	}
	
    
}